# -*- encoding: utf-8 -*-

Config = {
	'skybox': [
		{
			'days': 1,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars10', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars10', 'empty', 'empty', 'empty'],
		},
		{
			'days': 3,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars10_20', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars20', 'empty', 'empty', 'empty'],
		},
		{
			'days': 4,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars20', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars20', 'empty', 'empty', 'empty'],
		},
		{
			'days': 6,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars20_30', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars30', 'empty', 'empty', 'empty'],
		},
		{
			'days': 7,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars30', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars30', 'empty', 'empty', 'empty'],
		},
		{
			'days': 9,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars30_50', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars50', 'empty', 'empty', 'empty'],
		},
		{
			'days': 11,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'mars/mars50_100', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'mars/mars100', 'empty', 'empty', 'empty'],
		},
		{
			'days': 12,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
		},
		{
			'days': 14,
			'startTime': 0,
			'endTime': 23500,
			'start': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab40', 'asteroid_belt/abf100', 'empty', 'empty'],
			'end': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab40', 'asteroid_belt/abf100', 'empty', 'empty'],
		},
		{
			'days': 17,
			'startTime': 0,
			'endTime': 23500,
			'start': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab40_60', 'asteroid_belt/abf100', 'empty', 'empty'],
			'end': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab60', 'asteroid_belt/abf100', 'empty', 'empty'],
		},
		{
			'days': 20,
			'startTime': 0,
			'endTime': 23500,
			'start': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab60_80', 'asteroid_belt/abf100', 'empty', 'empty'],
			'end': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab80', 'asteroid_belt/abf100', 'empty', 'empty'],
		},
		{
			'days': 22,
			'startTime': 0,
			'endTime': 23500,
			'start': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab80_100', 'asteroid_belt/abf100', 'empty', 'empty'],
			'end': ['asteroid_belt/abf100', 'asteroid_belt/abf100', 'asteroid_belt/ab100', 'asteroid_belt/abf100', 'empty', 'empty'],
		},
		{
			'days': 23,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
		},
		{
			'days': 25,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter10', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter10', 'empty', 'empty', 'empty'],
		},
		{
			'days': 27,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter10_20', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter20', 'empty', 'empty', 'empty'],
		},
		{
			'days': 31,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter20_40', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter40', 'empty', 'empty', 'empty'],
		},
		{
			'days': 35,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter40_60', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter60', 'empty', 'empty', 'empty'],
		},
		{
			'days': 39,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter60_80', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter80', 'empty', 'empty', 'empty'],
		},
		{
			'days': 42,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'jupiter/jupiter80_100', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'jupiter/jupiter100', 'empty', 'empty', 'empty'],
		},
		{
			'days': 43,
			'startTime': 0,
			'endTime': 23500,
			'start': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
			'end': ['empty', 'empty', 'empty', 'empty', 'empty', 'empty'],
		},
	]
}
