# -*- coding: UTF-8 -*-

"""
物品的EMC值config
包含添加 修改物品EMC方法
"""

# region 原版物品EMC
_ItemsEMC = {
	('minecraft:tnt_minecart', 0): ['TNT矿车', 2244],
	('minecraft:trident', 0): ['三叉戟', 16463],
	('minecraft:nether_star', 0): ['下界之星', 139264],
	('minecraft:netherite_ingot', 0): ['下界合金锭', 57344],
	('minecraft:netherite_sword', 0): ['下界合金剑', 81268],
	('minecraft:netherite_block', 0): ['下界合金块', 608247],
	('minecraft:netherite_helmet', 0): ['下界合金头盔', 106060],
	('minecraft:netherite_leggings', 0): ['下界合金护腿', 122405],
	('minecraft:netherite_axe', 0): ['下界合金斧头', 89469],
	('minecraft:netherite_scrap', 0): ['下界合金碎片', 12288],
	('minecraft:netherite_chestplate', 0): ['下界合金胸甲', 130597],
	('minecraft:netherite_hoe', 0): ['下界合金锄头', 81272],
	('minecraft:netherite_shovel', 0): ['下界合金锹', 73076],
	('minecraft:netherite_pickaxe', 0): ['下界合金镐', 89469],
	('minecraft:netherite_boots', 0): ['下界合金靴子', 97811],
	('minecraft:netherrack', 0): ['下界岩', 1],
	('minecraft:nether_wart', 0): ['下界疣', 24],
	('minecraft:nether_wart_block', 0): ['下界疣方块', 216],
	('minecraft:quartz', 0): ['下界石英', 256],
	('minecraft:quartz_ore', 0): ['下界石英矿石', 286],
	('minecraft:netherbrick', 0): ['下界砖', 1],
	('minecraft:nether_brick_fence', 0): ['下界砖围墙', 3],
	('minecraft:nether_brick', 0): ['下界砖块', 4],
	('minecraft:nether_sprouts', 0): ['下界芽', 1],
	('minecraft:nether_gold_ore', 0): ['下界金矿石', 2048],
	('minecraft:red_nether_brick', 0): ['红色下界砖', 50],
	('minecraft:cracked_nether_bricks', 0): ['裂下界砖', 4],
	('minecraft:chiseled_nether_bricks', 0): ['錾制下界砖', 4],
	('minecraft:totem_of_undying', 0): ['不死图腾', 6666],
	('minecraft:jungle_pressure_plate', 0): ['丛林压力板', 16],
	('minecraft:jungle_sign', 0): ['丛林告示牌', 17],
	('minecraft:jungle_button', 0): ['丛林按钮', 8],
	('minecraft:jungle_fence_gate', 0): ['丛林木围墙门', 32],
	('minecraft:jungle_stairs', 0): ['丛林木楼梯', 12],
	('minecraft:jungle_boat', 0): ['丛林木船', 56],
	('minecraft:jungle_door', 0): ['丛林木门', 16],
	('minecraft:jungle_trapdoor', 0): ['丛林活板门', 24],
	('minecraft:amethyst_cluster', 0): ['紫水晶簇', 32],
	('minecraft:medium_amethyst_bud', 0): ['中型紫晶芽', 32],
	('minecraft:amethyst_shard', 0): ['紫水晶碎片', 32],
	('minecraft:large_amethyst_bud', 0): ['大型紫晶芽', 32],
	('minecraft:amethyst_block', 0): ['紫水晶方块', 128],
	('minecraft:small_amethyst_bud', 0): ['小型紫水晶芽', 32],
	('minecraft:budding_amethyst', 0): ['紫水晶母岩', 32],
	('minecraft:oak_planks', 0): ['橡木木板', 8],
	('minecraft:cobblestone_wall', 0): ['圆石墙', 1],
	('minecraft:double_stone_slab', 0): ['平滑石台阶', 1],
	('minecraft:double_stone_slab2', 0): ['红沙石台阶', 2],
	('minecraft:double_stone_slab3', 0): ['末地石砖台阶', 1],
	('minecraft:double_stone_slab4', 0): ['苔石砖台阶', 1],
	('minecraft:wooden_slab', 0): ['橡木台阶', 4],
	('minecraft:book', 0): ['书', 160],
	('minecraft:filled_map', 0): ['打开的地图', 1344],
	('minecraft:writable_book', 0): ['书与笔', 216],
	('minecraft:bookshelf', 0): ['书架', 528],
	('minecraft:spruce_pressure_plate', 0): ['云杉压力板', 16],
	('minecraft:spruce_fence_gate', 0): ['云杉围墙门', 32],
	('minecraft:spruce_button', 0): ['云杉按钮', 8],
	('minecraft:spruce_sign', 0): ['云杉木告示牌', 16],
	('minecraft:spruce_stairs', 0): ['云杉木楼梯', 12],
	('minecraft:spruce_boat', 0): ['云杉木船', 56],
	('minecraft:spruce_door', 0): ['云杉木门', 16],
	('minecraft:spruce_trapdoor', 0): ['云杉活板门', 24],
	('minecraft:cactus', 0): ['仙人掌', 8],
	('minecraft:observer', 0): ['侦测器', 484],
	('minecraft:beacon', 0): ['信标', 139461],
	('minecraft:rabbit_hide', 0): ['兔子皮', 16],
	('minecraft:rabbit_foot', 0): ['兔子腿', 128],
	('minecraft:rabbit_stew', 0): ['兔肉煲', 230],
	('minecraft:farmland', 0): ['农田', 2],
	('minecraft:ice', 0): ['冰', 1],
	('minecraft:wither_rose', 0): ['凋零玫瑰', 16],
	('minecraft:tuff', 0): ['凝灰岩', 4],
	('minecraft:stonecutter_block', 0): ['切石机', 259],
	('minecraft:cartography_table', 0): ['制图台', 96],
	('minecraft:mob_spawner', 0): ['刷怪笼', 66666],
	('minecraft:shears', 0): ['剪刀', 512],
	('minecraft:golden_rail', 0): ['动力铁轨', 2048],
	('minecraft:pumpkin', 0): ['南瓜', 144],
	('minecraft:pumpkin_pie', 0): ['南瓜派', 192],
	('minecraft:lit_pumpkin', 0): ['南瓜灯', 177],
	('minecraft:pumpkin_seeds', 0): ['南瓜种子', 144],
	('minecraft:wooden_pressure_plate', 0): ['压力板', 16],
	('minecraft:stripped_jungle_log', 0): ['去皮丛林原木', 32],
	('minecraft:stripped_spruce_log', 0): ['去皮云杉原木', 32],
	('minecraft:stripped_birch_log', 0): ['去皮桦树原木', 32],
	('minecraft:stripped_oak_log', 0): ['去皮橡树原木', 32],
	('minecraft:stripped_dark_oak_log', 0): ['去皮深色橡树原木', 32],
	('minecraft:stripped_crimson_hyphae', 0): ['去皮绯红菌丝', 42],
	('minecraft:stripped_crimson_stem', 0): ['去皮绯红菌柄', 32],
	('minecraft:stripped_warped_stem', 0): ['去皮诡异茎', 32],
	('minecraft:stripped_warped_hyphae', 0): ['去皮诡异菌丝', 42],
	('minecraft:stripped_acacia_log', 0): ['去皮金合欢原木', 32],
	('minecraft:glow_lichen', 0): ['发光地衣', 8],
	('minecraft:glow_ink_sac', 0): ['荧光墨囊', 400],
	('minecraft:glow_berries', 0): ['发光浆果', 16],
	('minecraft:glow_frame', 0): ['发光物品展示框', 128],
	('minecraft:dispenser', 0): ['发射器', 119],
	('minecraft:fermented_spider_eye', 0): ['发酵蛛眼', 172],
	('minecraft:cocoa_beans', 0): ['可可豆', 64],
	('minecraft:double_plant', 0): ['向日葵', 32],
	('minecraft:name_tag', 0): ['命名牌', 192],
	('minecraft:magenta_glazed_terracotta', 0): ['品红色带釉陶瓦', 65],
	('minecraft:magenta_dye', 0): ['品红色染料', 16],
	('minecraft:crying_obsidian', 0): ['哭泣的黑曜石', 768],
	('minecraft:jukebox', 0): ['唱片机', 8256],
	('minecraft:splash_potion', 0): ['喷溅水瓶', 65],
	('minecraft:cobblestone', 0): ['圆石', 1],
	('minecraft:stone_stairs', 0): ['圆石楼梯', 1],
	('minecraft:hanging_roots', 0): ['垂根', 4],
	('minecraft:weeping_vines', 0): ['垂泪藤', 8],
	('minecraft:bedrock', 0): ['基岩', 6666],
	('minecraft:composter', 0): ['堆肥箱', 28],
	('minecraft:ink_sac', 0): ['墨囊', 16],
	('minecraft:big_dripleaf', 0): ['大型垂滴叶', 1],
	('minecraft:milk_bucket', 0): ['奶桶', 784],
	('minecraft:spore_blossom', 0): ['孢子花', 64],
	('minecraft:small_dripleaf_block', 0): ['小型垂滴叶', 1],
	('minecraft:wheat', 0): ['小麦', 24],
	('minecraft:magma', 0): ['岩浆方块', 64],
	('minecraft:lava_bucket', 0): ['岩浆桶', 832],
	('minecraft:magma_cream', 0): ['岩浆膏', 800],
	('minecraft:crafting_table', 0): ['工作台', 32],
	('minecraft:dried_kelp', 0): ['干海带', 1],
	('minecraft:dried_kelp_block', 0): ['干海带块', 9],
	('minecraft:hay_block', 0): ['干草块', 216],
	('minecraft:smooth_basalt', 0): ['平滑玄武岩', 4],
	('minecraft:smooth_stone', 0): ['平滑石', 1],
	('minecraft:phantom_membrane', 0): ['幻翼膜', 192],
	('minecraft:bow', 0): ['弓', 48],
	('minecraft:crossbow', 0): ['弩', 426],
	('minecraft:ghast_tear', 0): ['恶魂之泪', 4096],
	('minecraft:flint_and_steel', 0): ['打火石', 260],
	('minecraft:dropper', 0): ['投掷器', 71],
	('minecraft:shield', 0): ['护盾', 304],
	('minecraft:lever', 0): ['拉杆', 5],
	('minecraft:lead', 0): ['拴绳', 40],
	('minecraft:compass', 0): ['指南针', 1088],
	('minecraft:detector_rail', 0): ['探测铁轨', 266],
	('minecraft:calcite', 0): ['方解石', 32],
	('minecraft:globe_banner_pattern', 0): ['旗帜图案', 512],
	('minecraft:skull_banner_pattern', 0): ['旗帜图案', 512],
	('minecraft:piglin_banner_pattern', 0): ['旗帜图案', 512],
	('minecraft:creeper_banner_pattern', 0): ["旗帜图案", 512],
	('minecraft:bordure_indented_banner_pattern', 0): ["旗帜图案", 512],
	('minecraft:field_masoned_banner_pattern', 0): ["旗帜图案", 512],
	('minecraft:flower_banner_pattern', 0): ["旗帜图案", 512],
	('minecraft:mojang_banner_pattern', 0): ["旗帜图案", 512],
	('minecraft:music_disc_pigstep', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_13', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_mall', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_chirp', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_cat', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_ward', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_otherside', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_far', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_wait', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_11', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_mellohi', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_strad', 0): ["音乐唱片", 2048],
	('minecraft:music_disc_blocks', 0): ["音乐唱片", 2048],
	('minecraft:bell', 0): ["钟", 8256],
	('minecraft:cookie', 0): ['曲奇', 22],
	('minecraft:spyglass', 0): ['望远镜', 8704],
	('minecraft:wooden_sword', 0): ['木剑', 20],
	('minecraft:wooden_axe', 0): ['木斧', 32],
	('minecraft:barrel', 0): ['木桶', 56],
	('minecraft:stick', 0): ['木棍', 4],
	('minecraft:charcoal', 0): ['木炭', 32],
	('minecraft:wooden_hoe', 0): ['木锄', 24],
	('minecraft:wooden_shovel', 0): ['木锹', 16],
	('minecraft:wooden_pickaxe', 0): ['木镐', 32],
	('minecraft:end_portal_frame', 0): ['末地传送门', 8],
	('minecraft:end_crystal', 0): ['末地水晶', 5895],
	('minecraft:end_rod', 0): ['末地烛', 432],
	('minecraft:end_stone', 0): ['末地石', 1],
	('minecraft:end_bricks', 0): ['末地石砖', 1],
	('minecraft:end_brick_stairs', 0): ['末地石砖楼梯', 1],
	('minecraft:ender_eye', 0): ['末影之眼', 1792],
	('minecraft:ender_pearl', 0): ['末影珍珠', 1024],
	('minecraft:ender_chest', 0): ['末影箱', 2304],
	('minecraft:azalea', 0): ['杜鹃花丛', 32],
	('minecraft:azalea_leaves', 0): ['杜鹃花叶', 1],
	('minecraft:deadbush', 0): ['枯萎的灌木', 1],
	('minecraft:birch_sign', 0): ['桦木告示牌', 16],
	('minecraft:birch_fence_gate', 0): ['桦木围墙门', 32],
	('minecraft:birch_stairs', 0): ['桦木楼梯', 12],
	('minecraft:birch_boat', 0): ['桦木船', 56],
	('minecraft:birch_door', 0): ['桦木门', 16],
	('minecraft:birch_pressure_plate', 0): ['桦树压力板', 16],
	('minecraft:birch_button', 0): ['桦树按钮', 8],
	('minecraft:birch_trapdoor', 0): ['桦树活板门', 24],
	('minecraft:bucket', 0): ['桶', 768],
	('minecraft:pufferfish_bucket', 0): ['桶装河豚', 832],
	('minecraft:tropical_fish_bucket', 0): ['桶装热带鱼', 832],
	('minecraft:salmon_bucket', 0): ['桶装鲑鱼', 832],
	('minecraft:cod_bucket', 0): ['桶装鳕鱼', 832],
	('minecraft:ladder', 0): ['梯子', 9],
	('minecraft:brown_glazed_terracotta', 0): ['棕色带釉陶瓦', 72],
	('minecraft:brown_dye', 0): ['棕色染料', 128],
	('minecraft:brown_mushroom', 0): ['棕色蘑菇', 32],
	('minecraft:orange_glazed_terracotta', 0): ['橙色带釉陶瓦', 66],
	('minecraft:orange_dye', 0): ['橙色染料', 16],
	('minecraft:wood', 0): ['橡木', 42],
	('minecraft:oak_sign', 0): ['橡木告示牌', 16],
	('minecraft:fence_gate', 0): ['橡木围墙门', 32],
	('minecraft:oak_stairs', 0): ['橡木楼梯', 12],
	('minecraft:trapdoor', 0): ['橡木活板门', 24],
	('minecraft:oak_boat', 0): ['橡木船', 56],
	('minecraft:wooden_door', 0): ['橡木门', 16],
	('minecraft:leaves', 0): ['橡树叶', 1],
	('minecraft:wooden_button', 0): ['橡树按钮', 8],
	('minecraft:sapling', 0): ['橡树苗', 32],
	('minecraft:coral_fan_dead', 0): ['死亡管珊瑚扇', 8],
	('minecraft:poisonous_potato', 0): ['毒马铃薯', 64],
	('minecraft:water_bucket', 0): ['水桶', 768],
	('minecraft:potion', 0): ['水瓶', 1],
	('minecraft:sand', 0): ['沙子', 1],
	('minecraft:sandstone', 0): ['沙石', 4],
	('minecraft:pufferfish', 0): ['河豚', 64],
	('minecraft:dirt', 0): ['泥土', 1],
	('minecraft:piston', 0): ['活塞', 348],
	('minecraft:light_weighted_pressure_plate', 0): ['测重压力板（轻型）', 4096],
	('minecraft:heavy_weighted_pressure_plate', 0): ['测重压力板（重型）', 512],
	('minecraft:packed_ice', 0): ['浮冰', 9],
	('minecraft:kelp', 0): ['海带', 1],
	('minecraft:sea_pickle', 0): ['海泡菜', 16],
	('minecraft:heart_of_the_sea', 0): ['海洋之心', 32768],
	('minecraft:sponge', 0): ['海绵', 64],
	('minecraft:seagrass', 0): ['海草', 1],
	('minecraft:turtle_helmet', 0): ['海龟壳', 160],
	('minecraft:turtle_egg', 0): ['海龟蛋', 192],
	('minecraft:silver_glazed_terracotta', 0): ['淡灰色带釉陶瓦', 66],
	('minecraft:light_gray_dye', 0): ['淡灰色染料', 16],
	('minecraft:light_blue_glazed_terracotta', 0): ['淡蓝色带釉陶瓦', 66],
	('minecraft:light_blue_dye', 0): ['淡蓝色染料', 16],
	('minecraft:deepslate_coal_ore', 0): ['深层煤矿石', 128],
	('minecraft:deepslate_redstone_ore', 0): ['深层红石矿石', 192],
	('minecraft:deepslate_emerald_ore', 0): ['深层绿宝石矿石', 16650],
	('minecraft:deepslate_gold_ore', 0): ['深层金矿石', 2000],
	('minecraft:deepslate_diamond_ore', 0): ['深层钻石矿石', 16364],
	('minecraft:deepslate_iron_ore', 0): ['深层铁矿石', 265],
	('minecraft:deepslate', 0): ['深板岩', 2],
	('minecraft:cobbled_deepslate', 0): ['深板岩圆石', 2],
	('minecraft:cobbled_deepslate_slab', 0): ['深板岩圆石台阶', 1],
	('minecraft:cobbled_deepslate_wall', 0): ['深板岩圆石墙', 1],
	('minecraft:deepslate_tiles', 0): ['深板岩瓦', 1],
	('minecraft:deepslate_tile_slab', 0): ['深板岩瓦台阶', 1],
	('minecraft:deepslate_tile_wall', 0): ['深板岩瓦墙', 1],
	('minecraft:deepslate_bricks', 0): ['深板岩砖', 2],
	('minecraft:deepslate_brick_slab', 0): ['深板岩砖台阶', 1],
	('minecraft:deepslate_brick_wall', 0): ['深板岩砖墙', 2],
	('minecraft:deepslate_lapis_ore', 0): ['深板岩青金石矿石', 5184],
	('minecraft:dark_oak_sign', 0): ['深色橡木告示牌', 16],
	('minecraft:dark_oak_fence_gate', 0): ['深色橡木围墙门', 32],
	('minecraft:dark_oak_stairs', 0): ['深色橡木楼梯', 12],
	('minecraft:dark_oak_boat', 0): ['深色橡木船', 56],
	('minecraft:dark_oak_door', 0): ['深色橡木门', 16],
	('minecraft:dark_oak_pressure_plate', 0): ['深色橡树压力板', 16],
	('minecraft:dark_oak_button', 0): ['深色橡树按钮', 8],
	('minecraft:dark_oak_trapdoor', 0): ['深色橡树活板门', 24],
	('minecraft:lingering_potion', 0): ['滯留水瓶', 2700],
	('minecraft:dripstone_block', 0): ['滴水石方块', 128],
	('minecraft:pointed_dripstone', 0): ['滴水石锥', 16],
	('minecraft:hopper', 0): ['漏斗', 1344],
	('minecraft:hopper_minecart', 0): ['漏斗矿车', 2624],
	('minecraft:shulker_shell', 0): ['潜匿之贝壳', 2048],
	('minecraft:conduit', 0): ['潮涌核心', 40960],
	('minecraft:activator_rail', 0): ['激活铁轨', 266],
	('minecraft:fire_charge', 0): ['火焰弹', 362],
	('minecraft:gunpowder', 0): ['火药', 192],
	('minecraft:lantern', 0): ['灯', 256],
	('minecraft:podzol', 0): ['灰化土', 2],
	('minecraft:gray_glazed_terracotta', 0): ['灰色带釉陶瓦', 66],
	('minecraft:gray_dye', 0): ['灰色染料', 28],
	('minecraft:soul_soil', 0): ['灵魂土', 4],
	('minecraft:soul_sand', 0): ['灵魂沙', 49],
	('minecraft:soul_torch', 0): ['灵魂火把', 32],
	('minecraft:soul_lantern', 0): ['灵魂灯', 256],
	('minecraft:soul_campfire', 0): ['灵魂营火', 128],
	('minecraft:tnt', 0): ['炸药', 1024],
	('minecraft:cauldron', 0): ['炼药锅', 1792],
	('minecraft:blaze_rod', 0): ['烈焰棒', 1536],
	('minecraft:blaze_powder', 0): ['烈焰粉', 768],
	('minecraft:smoker', 0): ['烟熏炉', 136],
	('minecraft:firework_rocket', 0): ['烟花火箭', 74],
	('minecraft:baked_potato', 0): ['烤马铃薯', 64],
	('minecraft:tropical_fish', 0): ['热带鱼', 64],
	('minecraft:firework_star', 0): ['焰火之星', 192],
	('minecraft:coal', 0): ['煤炭', 128],
	('minecraft:coal_block', 0): ['煤炭块', 1152],
	('minecraft:coal_ore', 0): ['煤矿石', 128],
	('minecraft:furnace', 0): ['熔炉', 8],
	('minecraft:cooked_rabbit', 0): ['熟兔肉', 64],
	('minecraft:cooked_beef', 0): ['牛排', 128],
	('minecraft:cooked_porkchop', 0): ['熟猪排', 64],
	('minecraft:cooked_mutton', 0): ['熟羊肉', 64],
	('minecraft:cooked_cod', 0): ['熟鱼', 64],
	('minecraft:cooked_salmon', 0): ['熟鲑鱼', 64],
	('minecraft:cooked_chicken', 0): ['熟鸡肉', 64],
	('minecraft:flint', 0): ['燧石', 4],
	('minecraft:popped_chorus_fruit', 0): ['爆裂紫颂果', 192],
	('minecraft:frame', 0): ['物品展示框', 96],
	('minecraft:basalt', 0): ['玄武岩', 4],
	('minecraft:red_flower', 0): ['玫瑰', 32],
	('minecraft:glass', 0): ['玻璃', 1],
	('minecraft:glass_pane', 0): ['玻璃板', 1],
	('minecraft:glass_bottle', 0): ['玻璃瓶', 1],
	('minecraft:sugar_cane', 0): ['甘蔗', 32],
	('minecraft:sweet_berries', 0): ['甜浆果', 16],
	('minecraft:beetroot', 0): ['甜菜根', 8],
	('minecraft:beetroot_soup', 0): ['甜菜根汤', 54],
	('minecraft:beetroot_seeds', 0): ['甜菜种子', 16],
	('minecraft:rabbit', 0): ['生兔肉', 64],
	('minecraft:beef', 0): ['生牛肉', 64],
	('minecraft:porkchop', 0): ['生猪排', 64],
	('minecraft:mutton', 0): ['生羊肉', 64],
	('minecraft:cod', 0): ['生鱼', 64],
	('minecraft:salmon', 0): ['生鲑鱼', 64],
	('minecraft:chicken', 0): ['生鸡肉', 64],
	('minecraft:painting', 0): ['画', 80],
	('minecraft:bed', 0): ['白床', 168],
	('minecraft:white_glazed_terracotta', 0): ['白色带釉陶瓦', 66],
	('minecraft:white_dye', 0): ['白色染料', 48],
	('minecraft:stained_hardened_clay', 0): ['白色陶瓦', 72],
	('minecraft:leather', 0): ['皮革', 64],
	('minecraft:leather_chestplate', 0): ['皮革上衣', 512],
	('minecraft:leather_helmet', 0): ['皮革帽子', 320],
	('minecraft:leather_leggings', 0): ['皮革裤子', 448],
	('minecraft:leather_boots', 0): ['皮革靴子', 256],
	('minecraft:leather_horse_armor', 0): ['皮马铠', 448],
	('minecraft:armor_stand', 0): ['盔甲架', 24],
	('minecraft:azalea_leaves_flowered', 0): ['盛开的杜鹃花叶', 1],
	('minecraft:flowering_azalea', 0): ['盛开的杜鹃花丛', 32],
	('minecraft:target', 0): ['目标', 472],
	('minecraft:waterlily', 0): ['睡莲', 16],
	('minecraft:stone_sword', 0): ['石剑', 6],
	('minecraft:stone_button', 0): ['石头按钮', 1],
	('minecraft:stone_axe', 0): ['石斧', 11],
	('minecraft:normal_stone_stairs', 0): ['石楼梯', 1],
	('minecraft:stonebrick', 0): ['石砖', 1],
	('minecraft:stone_brick_stairs', 0): ['石砖楼梯', 1],
	('minecraft:quartz_block', 0): ['石英块', 1024],
	('minecraft:quartz_bricks', 0): ['石英砖', 1024],
	('minecraft:stone_pressure_plate', 0): ['石质压力板', 2],
	('minecraft:stone_hoe', 0): ['石锄', 10],
	('minecraft:stone_shovel', 0): ['石锹', 9],
	('minecraft:stone_pickaxe', 0): ['石镐', 11],
	('minecraft:minecart', 0): ['矿车', 1280],
	('minecraft:gravel', 0): ['沙砾', 4],
	('minecraft:grindstone', 0): ['砂轮', 24],
	('minecraft:brick', 0): ['砖', 16],
	('minecraft:brick_block', 0): ['砖块', 64],
	('minecraft:brick_stairs', 0): ['砖块楼梯', 96],
	('minecraft:bowl', 0): ['碗', 6],
	('minecraft:lodestone', 0): ['磁石', 270340],
	('minecraft:polished_deepslate', 0): ['磨制深板岩', 2],
	('minecraft:polished_deepslate_slab', 0): ['磨制深板岩台阶', 1],
	('minecraft:polished_deepslate_wall', 0): ['磨制深板岩墙', 2],
	('minecraft:polished_basalt', 0): ['磨制玄武岩', 4],
	('minecraft:polished_blackstone', 0): ['磨制黑石', 4],
	('minecraft:polished_blackstone_pressure_plate', 0): ['磨制黑石压力板', 8],
	('minecraft:polished_blackstone_slab', 0): ['磨制黑石台阶', 2],
	('minecraft:polished_blackstone_wall', 0): ['磨制黑石墙', 4],
	('minecraft:polished_blackstone_button', 0): ['磨制黑石按钮', 4],
	('minecraft:polished_blackstone_bricks', 0): ['磨制黑石砖', 4],
	('minecraft:polished_blackstone_brick_slab', 0): ['磨制黑石砖块台阶', 2],
	('minecraft:polished_blackstone_brick_wall', 0): ['磨制黑石砖墙', 4],
	('minecraft:wheat_seeds', 0): ['种子', 16],
	('minecraft:empty_map', 0): ['空白地图', 1344],
	('minecraft:bamboo', 0): ['竹子', 32],
	('minecraft:coral_block', 0): ['管珊瑚块', 64],
	('minecraft:coral_fan', 0): ['管珊瑚扇', 16],
	('minecraft:arrow', 0): ['箭', 14],
	('minecraft:chest', 0): ['箱子', 64],
	('minecraft:powder_snow_bucket', 0): ['细雪桶', 784],
	('minecraft:pink_glazed_terracotta', 0): ['粉红色带釉陶瓦', 66],
	('minecraft:pink_dye', 0): ['粉红色染料', 4],
	('minecraft:raw_gold', 0): ['粗金', 2048],
	('minecraft:raw_gold_block', 0): ['粗金块', 18432],
	('minecraft:raw_iron', 0): ['粗铁', 256],
	('minecraft:raw_iron_block', 0): ['粗铁块', 2304],
	('minecraft:clay_ball', 0): ['黏土', 16],
	('minecraft:clay', 0): ['黏土块', 64],
	('minecraft:sticky_piston', 0): ['粘性活塞', 380],
	('minecraft:slime', 0): ['粘液块', 288],
	('minecraft:slime_ball', 0): ['粘液球', 32],
	('minecraft:sugar', 0): ['糖', 16],
	('minecraft:purpur_block', 0): ['紫珀块', 192],
	('minecraft:purple_glazed_terracotta', 0): ['紫色带釉陶瓦', 66],
	('minecraft:purple_dye', 0): ['紫色染料', 436],
	('minecraft:chorus_fruit', 0): ['紫颂果', 192],
	('minecraft:chorus_plant', 0): ['紫颂植物', 60],
	('minecraft:chorus_flower', 0): ['紫颂花', 96],
	('minecraft:red_sandstone', 0): ['红沙石', 4],
	('minecraft:repeater', 0): ['红石中继器', 203],
	('minecraft:redstone_block', 0): ['红石块', 576],
	('minecraft:comparator', 0): ['红石比较器', 557],
	('minecraft:redstone_torch', 0): ['红石火把', 68],
	('minecraft:redstone_lamp', 0): ['红石灯', 1792],
	('minecraft:redstone_ore', 0): ['红石矿石', 192],
	('minecraft:redstone', 0): ['红石粉', 63],
	('minecraft:red_glazed_terracotta', 0): ['红色带釉陶瓦', 66],
	('minecraft:red_dye', 0): ['红色染料', 8],
	('minecraft:red_mushroom', 0): ['红色蘑菇', 32],
	('minecraft:red_mushroom_block', 0): ['红色蘑菇方块', 8],
	('minecraft:paper', 0): ['纸', 32],
	('minecraft:string', 0): ['线', 2],
	('minecraft:loom', 0): ['织布机', 40],
	('minecraft:tripwire_hook', 0): ['绊线钩', 134],
	('minecraft:crimson_pressure_plate', 0): ['绯红压力板', 16],
	('minecraft:crimson_slab', 0): ['绯红台阶', 4],
	('minecraft:crimson_sign', 0): ['绯红告示牌', 17],
	('minecraft:crimson_fence', 0): ['绯红围墙', 12],
	('minecraft:crimson_fence_gate', 0): ['绯红围墙大门', 32],
	('minecraft:crimson_button', 0): ['绯红按钮', 8],
	('minecraft:crimson_planks', 0): ['绯红木板', 8],
	('minecraft:crimson_trapdoor', 0): ['绯红活板门', 24],
	('minecraft:crimson_fungus', 0): ['绯红真菌', 32],
	('minecraft:crimson_hyphae', 0): ['绯红菌丝', 85],
	('minecraft:crimson_nylium', 0): ['绯红菌岩', 1],
	('minecraft:crimson_stem', 0): ['绯红菌柄', 32],
	('minecraft:crimson_roots', 0): ['绯红菌索', 1],
	('minecraft:crimson_door', 0): ['绯红门', 16],
	('minecraft:crimson_stairs', 0): ['绯红阶梯', 12],
	('minecraft:emerald', 0): ['绿宝石', 16384],
	('minecraft:emerald_block', 0): ['绿宝石块', 147456],
	('minecraft:emerald_ore', 0): ['绿宝石矿石', 16650],
	('minecraft:green_glazed_terracotta', 0): ['绿色带釉陶瓦', 66],
	('minecraft:green_dye', 0): ['绿色染料', 8],
	('minecraft:twisting_vines', 0): ['缠怨藤', 8],
	('minecraft:dirt_with_roots', 0): ['缠根泥土', 5],
	('minecraft:axolotl_bucket', 0): ['美西螈桶', 1024],
	('minecraft:feather', 0): ['羽毛', 48],
	('minecraft:carrot', 0): ['胡萝卜', 64],
	('minecraft:carrot_on_a_stick', 0): ['胡萝卜钓竿', 100],
	('minecraft:scaffolding', 0): ['脚手架', 32],
	('minecraft:rotten_flesh', 0): ['腐肉', 32],
	('minecraft:flower_pot', 0): ['花盆', 48],
	('minecraft:mossy_cobblestone', 0): ['苔圆石', 9],
	('minecraft:moss_carpet', 0): ['苔藓地毯', 8],
	('minecraft:moss_block', 0): ['苔藓块', 12],
	('minecraft:apple', 0): ['苹果', 128],
	('minecraft:grass_path', 0): ['草径', 1],
	('minecraft:grass', 0): ['草方块', 1],
	('minecraft:mycelium', 0): ['菌丝', 2],
	('minecraft:shroomlight', 0): ['菌光体', 416],
	('minecraft:glowstone', 0): ['荧石', 1536],
	('minecraft:glowstone_dust', 0): ['荧石粉', 384],
	('minecraft:campfire', 0): ['营火', 236],
	('minecraft:yellow_flower', 0): ['蒲公英', 16],
	('minecraft:blue_ice', 0): ['蓝冰', 81],
	('minecraft:blue_glazed_terracotta', 0): ['蓝色带釉陶瓦', 172],
	('minecraft:blue_dye', 0): ['蓝色染料', 864],
	('minecraft:tallgrass', 0): ['蕨', 1],
	('minecraft:vine', 0): ['藤蔓', 8],
	('minecraft:brown_mushroom_block', 0): ['蘑菇', 32],
	('minecraft:mushroom_stew', 0): ['蘑菇煲', 70],
	('minecraft:cake', 0): ['蛋糕', 2450],
	('minecraft:bee_nest', 0): ['蜂巢', 128],
	('minecraft:beehive', 0): ['蜂箱', 102],
	('minecraft:honey_block', 0): ['蜂蜜方块', 196],
	('minecraft:honey_bottle', 0): ['蜂蜜瓶', 50],
	('minecraft:spider_eye', 0): ['蜘蛛眼', 128],
	('minecraft:web', 0): ['蜘蛛网', 12],
	('minecraft:honeycomb', 0): ['蜜脾', 16],
	('minecraft:honeycomb_block', 0): ['蜜脾块', 64],
	('minecraft:infested_deepslate', 0): ['被虫蚀的深板岩', 8],
	('minecraft:monster_egg', 0): ['被虫蚀的石头', 6],
	('minecraft:cracked_polished_blackstone_bricks', 0): ['裂磨制黑石砖', 4],
	('minecraft:cracked_deepslate_tiles', 0): ['裂纹深板岩瓦', 2],
	('minecraft:cracked_deepslate_bricks', 0): ['裂纹深板岩砖', 2],
	('minecraft:melon_block', 0): ['西瓜', 1296],
	('minecraft:melon_slice', 0): ['西瓜片', 16],
	('minecraft:melon_seeds', 0): ['西瓜种子', 144],
	('minecraft:lectern', 0): ['讲台', 544],
	('minecraft:warped_pressure_plate', 0): ['诡异压力板', 16],
	('minecraft:warped_slab', 0): ['诡异台阶', 4],
	('minecraft:warped_sign', 0): ['诡异告示牌', 17],
	('minecraft:warped_fence', 0): ['诡异围墙', 12],
	('minecraft:warped_fence_gate', 0): ['诡异围墙大门', 32],
	('minecraft:warped_button', 0): ['诡异按钮', 8],
	('minecraft:warped_planks', 0): ['诡异木板', 8],
	('minecraft:warped_roots', 0): ['诡异根', 1],
	('minecraft:warped_trapdoor', 0): ['诡异活板门', 24],
	('minecraft:warped_wart_block', 0): ['诡异疣方块', 216],
	('minecraft:warped_fungus', 0): ['诡异真菌', 32],
	('minecraft:warped_fungus_on_a_stick', 0): ['诡异真菌钓竿', 68],
	('minecraft:warped_stem', 0): ['诡异茎', 32],
	('minecraft:warped_hyphae', 0): ['诡异菌丝', 42],
	('minecraft:warped_nylium', 0): ['诡异菌岩', 2],
	('minecraft:warped_door', 0): ['诡异门', 16],
	('minecraft:warped_stairs', 0): ['诡异阶梯', 12],
	('minecraft:chest_minecart', 0): ['运输矿车', 1344],
	('minecraft:ancient_debris', 0): ['远古残骸', 66366],
	('minecraft:fletching_table', 0): ['造箭台', 40],
	('minecraft:lightning_rod', 0): ['避雷针', 768],
	('minecraft:brewing_stand', 0): ['酿造台', 1539],
	('minecraft:respawn_anchor', 0): ['重生锚', 9216],
	('minecraft:golden_sword', 0): ['金剑', 4100],
	('minecraft:acacia_pressure_plate', 0): ['金合欢压力板', 16],
	('minecraft:acacia_button', 0): ['金合欢按钮', 8],
	('minecraft:acacia_sign', 0): ['金合欢木告示牌', 17],
	('minecraft:acacia_fence_gate', 0): ['金合欢木栅栏门', 32],
	('minecraft:acacia_stairs', 0): ['金合欢木楼梯', 12],
	('minecraft:acacia_door', 0): ['金合欢木门', 16],
	('minecraft:leaves2', 0): ['金合欢树叶', 1],
	('minecraft:acacia_trapdoor', 0): ['金合欢活板门', 24],
	('minecraft:acacia_boat', 0): ['金合欢船', 56],
	('minecraft:gold_block', 0): ['金块', 18432],
	('minecraft:golden_helmet', 0): ['金头盔', 10240],
	('minecraft:golden_leggings', 0): ['金护腿', 14336],
	('minecraft:golden_axe', 0): ['金斧', 6152],
	('minecraft:gold_ore', 0): ['金矿石', 2058],
	('minecraft:gold_nugget', 0): ['金粒', 227],
	('minecraft:golden_chestplate', 0): ['金胸甲', 16384],
	('minecraft:golden_apple', 0): ['金苹果', 16512],
	('minecraft:golden_carrot', 0): ['金萝卜', 1880],
	('minecraft:golden_hoe', 0): ['金锄', 4104],
	('minecraft:gold_ingot', 0): ['金锭', 2048],
	('minecraft:golden_shovel', 0): ['金锹', 2056],
	('minecraft:golden_pickaxe', 0): ['金镐', 6152],
	('minecraft:golden_boots', 0): ['金靴子', 8192],
	('minecraft:chiseled_deepslate', 0): ['錾制深板岩', 2],
	('minecraft:chiseled_polished_blackstone', 0): ['錾制磨制黑石', 4],
	('minecraft:fishing_rod', 0): ['钓鱼竿', 36],
	('minecraft:clock', 0): ['钟', 8256],
	('minecraft:diamond', 0): ['钻石', 8192],
	('minecraft:diamond_sword', 0): ['钻石剑', 16388],
	('minecraft:diamond_block', 0): ['钻石块', 73728],
	('minecraft:diamond_helmet', 0): ['钻石头盔', 40960],
	('minecraft:diamond_leggings', 0): ['钻石护腿', 57344],
	('minecraft:diamond_axe', 0): ['钻石斧', 24584],
	('minecraft:diamond_ore', 0): ['钻石矿石', 16364],
	('minecraft:diamond_chestplate', 0): ['钻石胸甲', 65536],
	('minecraft:diamond_hoe', 0): ['钻石锄', 16392],
	('minecraft:diamond_shovel', 0): ['钻石锹', 8200],
	('minecraft:diamond_pickaxe', 0): ['钻石镐', 24584],
	('minecraft:diamond_boots', 0): ['钻石靴子', 32768],
	('minecraft:diamond_horse_armor', 0): ['钻石马铠', 65536],
	('minecraft:iron_sword', 0): ['铁剑', 516],
	('minecraft:iron_block', 0): ['铁块', 2304],
	('minecraft:iron_helmet', 0): ['铁头盔', 1280],
	('minecraft:iron_leggings', 0): ['铁护腿', 1792],
	('minecraft:iron_axe', 0): ['铁斧', 776],
	('minecraft:iron_bars', 0): ['铁栏杆', 96],
	('minecraft:iron_ore', 0): ['铁矿石', 265],
	('minecraft:anvil', 0): ['铁砧', 7936],
	('minecraft:iron_nugget', 0): ['铁粒', 28],
	('minecraft:iron_chestplate', 0): ['铁胸甲', 2048],
	('minecraft:rail', 0): ['铁轨', 96],
	('minecraft:iron_hoe', 0): ['铁锄', 520],
	('minecraft:iron_ingot', 0): ['铁锭', 256],
	('minecraft:iron_shovel', 0): ['铁锹', 264],
	('minecraft:iron_pickaxe', 0): ['铁镐', 776],
	('minecraft:iron_door', 0): ['铁门', 512],
	('minecraft:iron_trapdoor', 0): ['铁陷阱门', 1024],
	('minecraft:iron_boots', 0): ['铁靴子', 1024],
	('minecraft:iron_horse_armor', 0): ['铁马铠', 2048],
	('minecraft:chain', 0): ['链', 312],
	('minecraft:chainmail_helmet', 0): ['锁链头盔', 1287],
	('minecraft:chainmail_leggings', 0): ['锁链护腿', 1799],
	('minecraft:chainmail_chestplate', 0): ['锁链胸甲', 2056],
	('minecraft:chainmail_boots', 0): ['锁链靴子', 1029],
	('minecraft:smithing_table', 0): ['锻造台', 544],
	('minecraft:gilded_blackstone', 0): ['镶金黑石', 233],
	('minecraft:glistering_melon_slice', 0): ['闪烁的西瓜片', 1832],
	('minecraft:daylight_detector', 0): ['阳光传感器', 1024],
	('minecraft:experience_bottle', 0): ['附魔之瓶', 26666],
	('minecraft:enchanted_book', 0): ['附魔书', 160],
	('minecraft:enchanting_table', 0): ['附魔台', 16800],
	('minecraft:enchanted_golden_apple', 0): ['附魔苹果', 147584],
	('minecraft:hardened_clay', 0): ['陶瓦', 64],
	('minecraft:trapped_chest', 0): ['陷阱箱', 198],
	('minecraft:carved_pumpkin', 0): ['雕刻南瓜', 144],
	('minecraft:snow', 0): ['雪', 4],
	('minecraft:snowball', 0): ['雪球', 1],
	('minecraft:cyan_glazed_terracotta', 0): ['青色带釉陶瓦', 65],
	('minecraft:cyan_dye', 0): ['青色染料', 436],
	('minecraft:lapis_lazuli', 0): ['青金石', 864],
	('minecraft:lapis_block', 0): ['青金石块', 7776],
	('minecraft:lapis_ore', 0): ['青金石矿石', 5184],
	('minecraft:bread', 0): ['面包', 72],
	('minecraft:saddle', 0): ['鞍', 192],
	('minecraft:elytra', 0): ['鞘翅', 10240],
	('minecraft:music_disc_stal', 0): ['音乐唱片', 2048],
	('minecraft:noteblock', 0): ['音符盒', 128],
	('minecraft:snow_layer', 0): ['顶层雪', 2],
	('minecraft:potato', 0): ['马铃薯', 64],
	('minecraft:bone', 0): ['骨头', 144],
	('minecraft:bone_block', 0): ['骨头方块', 432],
	('minecraft:bone_meal', 0): ['骨粉', 48],
	('minecraft:skull', 0): ['骷髅模型', 256],
	('minecraft:blast_furnace', 0): ['高炉', 1291],
	('minecraft:scute', 0): ['鳞甲', 96],
	('minecraft:egg', 0): ['鸡蛋', 32],
	('minecraft:nautilus_shell', 0): ['鹦鹉螺壳', 1024],
	('minecraft:lime_glazed_terracotta', 0): ['黄绿色带釉陶瓦', 65],
	('minecraft:lime_dye', 0): ['黄绿色染料', 27],
	('minecraft:yellow_glazed_terracotta', 0): ['黄色带釉陶瓦', 66],
	('minecraft:yellow_dye', 0): ['黄色染料', 16],
	('minecraft:golden_horse_armor', 0): ['黄金马铠', 16384],
	('minecraft:obsidian', 0): ['黑曜石', 64],
	('minecraft:blackstone', 0): ['黑石', 4],
	('minecraft:black_glazed_terracotta', 0): ['黑色带釉陶瓦', 66],
	('minecraft:banner', 0): ['黑色旗帜', 292],
	('minecraft:black_dye', 0): ['黑色染料', 8],
	('minecraft:dragon_breath', 0): ['龙息', 2],
	('minecraft:dragon_egg', 0): ['龙蛋', 264114],
	('minecraft:cherry_leaves', 0) : ['樱花树叶', 1],
	('minecraft:mangrove_leaves', 0) : ['红树林树叶', 1],
	('minecraft:torchflower_seeds', 0) : ['火把花种子', 16],
	('minecraft:torchflower', 0) : ['火把花', 16],
	('minecraft:pitcher_pod', 0) : ['猪笼草荚果', 32],
	('minecraft:warped_wall_sign', 0) : ['诡异告示牌', 17],
	('minecraft:tadpole_bucket', 0) : ['蝌蚪桶', 832],
	('minecraft:standing_banner', 0) : ['旗帜', 292],
	('minecraft:mangrove_roots', 0) : ['红树根', 4],
	('minecraft:crimson_double_slab', 0) : ['绯红木台阶', 4],
	('minecraft:goat_horn', 0) : ['山羊角', 96],
	('minecraft:sculk_catalyst', 0) : ['幽匿催发体', 8040],
	('minecraft:frog_spawn', 0) : ['青蛙卵', 16],
	('minecraft:mangrove_propagule', 0) : ['红树胎生苗', 32],
	('minecraft:warped_double_slab', 0) : ['诡异台阶', 4],
	('minecraft:disc_fragment_5', 0) : ['唱片残片', 227],
	('minecraft:echo_shard', 0) : ['回响碎片', 192],
	('minecraft:cherry_button', 0) : ['樱花木按钮', 8],
	('minecraft:mangrove_button', 0) : ['红树林按钮', 8],
	('minecraft:stripped_cherry_wood', 0) : ['去皮樱花木', 128],
	('minecraft:mangrove_wood', 0) : ['红树林木头', 128],
	('minecraft:blackstone_wall', 0) : ['黑石墙', 24],
	('minecraft:mangrove_pressure_plate', 0) : ['红树林压力板', 16],

	('minecraft:blade_pottery_sherd', 0) : ['利刃纹样陶片', 216],
	('minecraft:explorer_pottery_sherd', 0) : ['探险纹样陶片', 216],
	('minecraft:angler_pottery_sherd', 0) : ['垂钓纹样陶片', 216],
	('minecraft:burn_pottery_sherd', 0) : ['烈焰纹样陶片', 216],
	('minecraft:danger_pottery_sherd', 0) : ['危机纹样陶片', 216],
	('minecraft:archer_pottery_sherd', 0) : ['弓箭纹样陶片', 216],
	('minecraft:arms_up_pottery_sherd', 0) : ['举臂纹样陶片', 216],
	('minecraft:brewer_pottery_sherd', 0) : ['佳酿纹样陶片', 216],
	('minecraft:friend_pottery_sherd', 0) : ['挚友纹样陶片', 216],
	('minecraft:heart_pottery_sherd', 0) : ['爱心纹样陶片', 216],
	('minecraft:heartbreak_pottery_sherd', 0) : ['心碎纹样陶片', 216],
	('minecraft:howl_pottery_sherd', 0) : ['狼嚎纹样陶片', 216],
	('minecraft:miner_pottery_sherd', 0) : ['采矿纹样陶片', 216],
	('minecraft:mourner_pottery_sherd', 0) : ['哀悼纹样陶片', 216],
	('minecraft:plenty_pottery_sherd', 0) : ['富饶纹样陶片', 216],
	('minecraft:prize_pottery_sherd', 0) : ['珍宝纹样陶片', 216],
	('minecraft:sheaf_pottery_sherd', 0) : ['麦捆纹样陶片', 216],
	('minecraft:shelter_pottery_sherd', 0) : ['树荫纹样陶片', 216],
	('minecraft:skull_pottery_sherd', 0) : ['头颅纹样陶片', 216],
	('minecraft:snort_pottery_sherd', 0) : ['嗅探纹样陶片', 216],

	('minecraft:mud_bricks', 0) : ['泥砖', 1],
	('minecraft:chiseled_bookshelf', 0) : ['雕纹书架', 48],
	('minecraft:mud_brick_wall', 0) : ['泥砖墙', 1],
	('minecraft:packed_mud', 0) : ['填充泥浆', 25],
	('minecraft:cherry_pressure_plate', 0) : ['樱花木压力板', 16],
	('minecraft:decorated_pot', 0) : ['饰纹陶罐', 64],
	('minecraft:boat', 0) : ['橡木船', 40],
	('minecraft:banner_pattern', 0) : ['旗帜图案', 5056],
	('minecraft:bamboo_block', 0) : ['竹子方块', 288],
	('minecraft:bamboo_button', 0) : ['竹制按钮', 8],
	('minecraft:shulker_box', 0) : ['白色潜影盒', 4216],
	('minecraft:wool', 0) : ['白色羊毛', 8],
	('minecraft:carpet', 0) : ['白色地毯', 96],
	('minecraft:fence', 0) : ['橡木栅栏', 40],
	('minecraft:mud_brick_stairs', 0) : ['泥砖楼梯', 0],
	('minecraft:stone_block_slab', 0) : ['平滑石台阶', 3],
	('minecraft:stone_block_slab2', 0) : ['红砂岩台阶', 12],
	('minecraft:stone_block_slab3', 0) : ['末地石砖台阶', 3],
	('minecraft:stone_block_slab4', 0) : ['苔石砖台阶', 3],
	('minecraft:tide_armor_trim_smithing_template', 0) : ['锻造模板', 58368],
	('minecraft:dune_armor_trim_smithing_template', 0) : ['锻造模板', 57348],
	('minecraft:coast_armor_trim_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:wild_armor_trim_smithing_template', 0) : ['锻造模板', 57353],
	('minecraft:vex_armor_trim_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:snout_armor_trim_smithing_template', 0) : ['锻造模板', 57348],
	('minecraft:rib_armor_trim_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:spire_armor_trim_smithing_template', 0) : ['锻造模板', 57536],
	('minecraft:silence_armor_trim_smithing_template', 0) : ['锻造模板', 57346],
	('minecraft:wayfinder_armor_trim_smithing_template', 0) : ['锻造模板', 57408],
	('minecraft:raiser_armor_trim_smithing_template', 0) : ['锻造模板', 57408],
	('minecraft:shaper_armor_trim_smithing_template', 0) : ['锻造模板', 57408],
	('minecraft:host_armor_trim_smithing_template', 0) : ['锻造模板', 57408],
	('minecraft:netherite_upgrade_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:sentry_armor_trim_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:eye_armor_trim_smithing_template', 0) : ['锻造模板', 57345],
	('minecraft:ward_armor_trim_smithing_template', 0) : ['锻造模板', 57346],
	('minecraft:tide_armor_trim_smithing_template', 0) : ['锻造模板', 29184],
	('minecraft:cherry_chest_boat', 0) : ['樱花木运输船', 64],
	('minecraft:cherry_hanging_sign', 0) : ['樱花木悬挂告示牌', 816],
	('minecraft:cherry_slab', 0) : ['樱花木台阶', 24],
	('minecraft:bamboo_slab', 0) : ['竹制台阶', 24],
	('minecraft:bamboo_mosaic_slab', 0) : ['竹制马赛克台阶', 24],
	('minecraft:bamboo_sign', 0) : ['竹制告示牌', 52],
	('minecraft:oak_hanging_sign', 0) : ['橡木悬挂告示牌', 816],
	('minecraft:spruce_hanging_sign', 0) : ['云杉木悬挂告示牌', 816],
	('minecraft:jungle_hanging_sign', 0) : ['丛林悬挂告示牌', 816],
	('minecraft:dark_oak_hanging_sign', 0) : ['深色橡木悬挂告示牌', 816],
	('minecraft:crimson_hanging_sign', 0) : ['绯红木悬挂告示牌', 816],
	('minecraft:warped_hanging_sign', 0) : ['翘曲悬挂告示牌', 816],
	('minecraft:mangrove_hanging_sign', 0) : ['红树林悬挂告示牌', 816],
	('minecraft:brush', 0) : ['刷子', 180],
	('minecraft:mangrove_boat', 0) : ['红树林船', 40],
	('minecraft:mangrove_slab', 0) : ['红树林台阶', 24],
	('minecraft:music_disc_5', 0) : ['音乐唱片', 2043],
	('minecraft:oak_chest_boat', 0) : ['橡木运输船', 120],
	('minecraft:birch_chest_boat', 0) : ['白桦木运输船', 120],
	('minecraft:cherry_boat', 0) : ['樱花木船', 40],
	('minecraft:mangrove_chest_boat', 0) : ['红树木运输船', 64],
	('minecraft:chest_boat', 0) : ['橡木运输船', 120],
	('minecraft:recovery_compass', 0) : ['追溯指针', 2624],
	('minecraft:acacia_hanging_sign', 0) : ['金合欢悬挂告示牌', 816],
	('minecraft:dark_oak_chest_boat', 0) : ['深色橡木运输船', 120],
	('minecraft:cherry_wood', 0) : ['樱花木', 128],
	('minecraft:suspicious_stew', 0) : ['迷之炖菜', 86],
	('minecraft:spruce_chest_boat', 0) : ['云杉木运输船', 120],
	('minecraft:mud_brick_slab', 0) : ['泥砖台阶', 16],
	('minecraft:mangrove_sign', 0) : ['红树林告示牌', 52],
	('minecraft:sculk', 0) : ['幽匿块', 16],
	('minecraft:birch_hanging_sign', 0) : ['白桦木悬挂告示牌', 816],
	('minecraft:bamboo_raft', 0) : ['竹筏', 40],
	('minecraft:cherry_sign', 0) : ['樱花木告示牌', 52],
	('minecraft:item.reeds', 0) : ['甘蔗', 16],
	('minecraft:blackstone_slab', 0) : ['黑石台阶', 12],
	('minecraft:acacia_chest_boat', 0) : ['金合欢木运输船', 120],
	('minecraft:muddy_mangrove_roots', 0) : ['沾泥的红树根', 5],
	('minecraft:bamboo_chest_raft', 0) : ['运输竹筏', 64],
	('minecraft:calibrated_sculk_sensor', 0) : ['校频幽匿感测体', 2776],
	('minecraft:bamboo_hanging_sign', 0) : ['竹制悬挂告示牌', 2352],
	('minecraft:stripped_mangrove_wood', 0) : ['去皮红树林木头', 128],
	('minecraft:jungle_chest_boat', 0) : ['丛林木运输船', 120],
	('minecraft:item.soul_campfire', 0) : ['灵魂营火', 128],
	('minecraft:bamboo_pressure_plate', 0) : ['竹制压力板', 16],

	('minecraft:goat_spawn_egg', 0) : ['山羊刷怪蛋', 6],
	('minecraft:wither_spawn_egg', 0) : ['凋灵刷怪蛋', 6],
	('minecraft:ender_dragon_spawn_egg', 0) : ['末影龙刷怪蛋', 6],
	('minecraft:glow_squid_spawn_egg', 0) : ['发光鱿鱼刷怪蛋', 6],
	('minecraft:villager_spawn_egg', 0) : ['村民刷怪蛋', 6],
	('minecraft:elder_guardian_spawn_egg', 0) : ['远古守卫者刷怪蛋', 6],
	('minecraft:chicken_spawn_egg', 0) : ['鸡刷怪蛋', 6],
	('minecraft:cow_spawn_egg', 0) : ['牛刷怪蛋', 6],
	('minecraft:pig_spawn_egg', 0) : ['猪刷怪蛋', 6],
	('minecraft:sheep_spawn_egg', 0) : ['羊刷怪蛋', 6],
	('minecraft:wolf_spawn_egg', 0) : ['狼刷怪蛋', 6],
	('minecraft:mooshroom_spawn_egg', 0) : ['哞菇刷怪蛋', 6],
	('minecraft:salmon_spawn_egg', 0) : ['鲑鱼刷怪蛋', 6],
	('minecraft:creeper_spawn_egg', 0) : ['苦力怕刷怪蛋', 6],
	('minecraft:enderman_spawn_egg', 0) : ['末影人刷怪蛋', 6],
	('minecraft:silverfish_spawn_egg', 0) : ['蠹虫刷怪蛋', 6],
	('minecraft:skeleton_spawn_egg', 0) : ['骷髅刷怪蛋', 6],
	('minecraft:pillager_spawn_egg', 0) : ['掠夺者刷怪蛋', 6],
	('minecraft:slime_spawn_egg', 0) : ['史莱姆刷怪蛋', 6],
	('minecraft:zombie_spawn_egg', 0) : ['僵尸刷怪蛋', 6],
	('minecraft:zombie_pigman_spawn_egg', 0) : ['僵尸猪灵刷怪蛋', 6],
	('minecraft:squid_spawn_egg', 0) : ['鱿鱼刷怪蛋', 6],
	('minecraft:ocelot_spawn_egg', 0) : ['豹猫刷怪蛋', 6],
	('minecraft:witch_spawn_egg', 0) : ['女巫刷怪蛋', 6],
	('minecraft:bat_spawn_egg', 0) : ['蝙蝠刷怪蛋', 6],
	('minecraft:ghast_spawn_egg', 0) : ['恶魂刷怪蛋', 6],
	('minecraft:magma_cube_spawn_egg', 0) : ['岩浆怪刷怪蛋', 6],
	('minecraft:blaze_spawn_egg', 0) : ['烈焰人刷怪蛋', 6],
	('minecraft:cave_spider_spawn_egg', 0) : ['洞穴蜘蛛刷怪蛋', 6],
	('minecraft:horse_spawn_egg', 0) : ['马刷怪蛋', 6],
	('minecraft:rabbit_spawn_egg', 0) : ['兔子刷怪蛋', 6],
	('minecraft:endermite_spawn_egg', 0) : ['末影螨刷怪蛋', 6],
	('minecraft:guardian_spawn_egg', 0) : ['守卫者刷怪蛋', 6],
	('minecraft:stray_spawn_egg', 0) : ['流浪者刷怪蛋', 6],
	('minecraft:husk_spawn_egg', 0) : ['尸壳刷怪蛋', 6],
	('minecraft:wither_skeleton_spawn_egg', 0) : ['凋灵骷髅刷怪蛋', 6],
	('minecraft:donkey_spawn_egg', 0) : ['驴刷怪蛋', 6],
	('minecraft:mule_spawn_egg', 0) : ['骡刷怪蛋', 6],
	('minecraft:skeleton_horse_spawn_egg', 0) : ['骷髅马刷怪蛋', 6],
	('minecraft:zombie_horse_spawn_egg', 0) : ['僵尸马刷怪蛋', 6],
	('minecraft:shulker_spawn_egg', 0) : ['潜影贝刷怪蛋', 6],
	('minecraft:npc_spawn_egg', 0) : ['NPC刷怪蛋', 6],
	('minecraft:polar_bear_spawn_egg', 0) : ['北极熊刷怪蛋', 6],
	('minecraft:llama_spawn_egg', 0) : ['羊驼刷怪蛋', 6],
	('minecraft:vindicator_spawn_egg', 0) : ['卫道士刷怪蛋', 6],
	('minecraft:evoker_spawn_egg', 0) : ['唤魔者刷怪蛋', 6],
	('minecraft:vex_spawn_egg', 0) : ['恼鬼刷怪蛋', 6],
	('minecraft:zombie_villager_spawn_egg', 0) : ['僵尸村民刷怪蛋', 6],
	('minecraft:parrot_spawn_egg', 0) : ['鹦鹉刷怪蛋', 6],
	('minecraft:tropical_fish_spawn_egg', 0) : ['热带鱼刷怪蛋', 6],
	('minecraft:cod_spawn_egg', 0) : ['鳕鱼刷怪蛋', 6],
	('minecraft:pufferfish_spawn_egg', 0) : ['河豚刷怪蛋', 6],
	('minecraft:drowned_spawn_egg', 0) : ['溺尸刷怪蛋', 6],
	('minecraft:dolphin_spawn_egg', 0) : ['海豚刷怪蛋', 6],
	('minecraft:turtle_spawn_egg', 0) : ['海龟刷怪蛋', 6],
	('minecraft:phantom_spawn_egg', 0) : ['幻翼刷怪蛋', 6],
	('minecraft:agent_spawn_egg', 0) : ['代理机器人刷怪蛋', 6],
	('minecraft:cat_spawn_egg', 0) : ['猫刷怪蛋', 6],
	('minecraft:panda_spawn_egg', 0) : ['熊猫刷怪蛋', 6],
	('minecraft:fox_spawn_egg', 0) : ['狐狸刷怪蛋', 6],
	('minecraft:wandering_trader_spawn_egg', 0) : ['流浪商人刷怪蛋', 6],
	('minecraft:ravager_spawn_egg', 0) : ['劫掠兽刷怪蛋', 6],
	('minecraft:bee_spawn_egg', 0) : ['蜜蜂刷怪蛋', 6],
	('minecraft:strider_spawn_egg', 0) : ['炽足兽刷怪蛋', 6],
	('minecraft:hoglin_spawn_egg', 0) : ['疣猪兽刷怪蛋', 6],
	('minecraft:piglin_spawn_egg', 0) : ['猪灵刷怪蛋', 6],
	('minecraft:zoglin_spawn_egg', 0) : ['僵尸疣猪兽刷怪蛋', 6],
	('minecraft:piglin_brute_spawn_egg', 0) : ['猪灵蛮兵刷怪蛋', 6],
	('minecraft:sniffer_spawn_egg', 0) : ['嗅探兽刷怪蛋', 6],
	('minecraft:axolotl_spawn_egg', 0) : ['美西螈刷怪蛋', 6],
	('minecraft:iron_golem_spawn_egg', 0) : ['铁傀儡刷怪蛋', 6],
	('minecraft:snow_golem_spawn_egg', 0) : ['雪傀儡刷怪蛋', 6],
	('minecraft:frog_spawn_egg', 0) : ['青蛙刷怪蛋', 6],
	('minecraft:tadpole_spawn_egg', 0) : ['蝌蚪刷怪蛋', 6],
	('minecraft:allay_spawn_egg', 0) : ['悦灵刷怪蛋', 6],
	('minecraft:trader_llama_spawn_egg', 0) : ['行商羊驼刷怪蛋', 6],
	('minecraft:camel_spawn_egg', 0) : ['骆驼刷怪蛋', 6],
	('minecraft:sniffer_egg', 0) : ['嗅探兽蛋', 6],
	('minecraft:spider_spawn_egg', 0) : ['蜘蛛刷怪蛋', 6],
	('minecraft:warden_spawn_egg', 0) : ['监守者刷怪蛋', 6],

	# region 非创造栏
	('minecraft:gray_candle_cake', 0) : ['带灰色蜡烛的蛋糕', 6],
	('minecraft:yellow_candle_cake', 0) : ['带黄色蜡烛的蛋糕', 6],
	('minecraft:cyan_candle_cake', 0) : ['带青色蜡烛的蛋糕', 6],
	('minecraft:magenta_candle_cake', 0) : ['带品红色蜡烛的蛋糕', 6],
	('minecraft:green_candle_cake', 0) : ['带绿色蜡烛的蛋糕', 6],
	('minecraft:light_blue_candle_cake', 0) : ['带淡蓝色蜡烛的蛋糕', 6],
	('minecraft:purple_candle_cake', 0) : ['带紫色蜡烛的蛋糕', 6],
	('minecraft:orange_candle_cake', 0) : ['带橙色蜡烛的蛋糕', 6],
	('minecraft:pink_candle_cake', 0) : ['带粉红色蜡烛的蛋糕', 6],
	('minecraft:black_candle_cake', 0) : ['带黑色蜡烛的蛋糕', 6],
	('minecraft:brown_candle_cake', 0) : ['带棕色蜡烛的蛋糕', 6],
	('minecraft:light_gray_candle_cake', 0) : ['带淡灰色蜡烛的蛋糕', 6],
	('minecraft:blue_candle_cake', 0) : ['带蓝色蜡烛的蛋糕', 6],
	('minecraft:candle_cake', 0) : ['带蜡烛的蛋糕', 6],
	('minecraft:white_candle_cake', 0) : ['带白色蜡烛的蛋糕', 6],
	('minecraft:lime_candle_cake', 0) : ['带黄绿色蜡烛的蛋糕', 6],
	('minecraft:red_candle_cake', 0) : ['带红色蜡烛的蛋糕', 6],

	('minecraft:cherry_wall_sign', 0) : ['tile.cherry_wall_sign.name', 1],
	('minecraft:lit_smoker', 0) : ['tile.lit_smoker.name', 1],
	('minecraft:chemical_heat', 0) : ['tile.chemical_heat.name', 1],
	('minecraft:bamboo_sapling', 0) : ['tile.bamboo_sapling.oak.name', 1],
	('minecraft:lit_deepslate_redstone_ore', 0) : ['tile.lit_deepslate_redstone_ore.name', 1],
	('minecraft:bamboo_standing_sign', 0) : ['tile.bamboo_standing_sign.name', 1],
	('minecraft:birch_wall_sign', 0) : ['tile.birch_wall_sign.name', 1],
	('minecraft:waxed_exposed_double_cut_copper_slab', 0) : ['tile.waxed_exposed_double_cut_copper_slab.name', 1],
	('minecraft:sticky_piston_arm_collision', 0) : ['tile.sticky_piston_arm_collision.name', 1],
	('minecraft:unpowered_comparator', 0) : ['tile.unpowered_comparator.name', 1],
	('minecraft:item.mangrove_door', 0) : ['tile.mangrove_door.name', 1],
	('minecraft:bubble_column', 0) : ['tile.bubble_column.name', 1],
	('minecraft:cherry_standing_sign', 0) : ['tile.cherry_standing_sign.name', 1],
	('minecraft:mangrove_wall_sign', 0) : ['tile.mangrove_wall_sign.name', 1],
	('minecraft:item.skull', 0) : ['tile.skull.name', 1],
	('minecraft:darkoak_wall_sign', 0) : ['tile.darkoak_wall_sign.name', 1],
	('minecraft:item.kelp', 0) : ['tile.kelp.name', 1],
	('minecraft:unpowered_repeater', 0) : ['tile.unpowered_repeater.name', 1],
	('minecraft:moving_block', 0) : ['tile.moving_block.name', 1],
	('minecraft:item.spruce_door', 0) : ['tile.spruce_door.name', 1],
	('minecraft:hard_glass', 0) : ['tile.hard_glass.name', 1],
	('minecraft:melon_stem', 0) : ['tile.melon_stem.name', 1],
	('minecraft:waxed_weathered_double_cut_copper_slab', 0) : ['tile.waxed_weathered_double_cut_copper_slab.name', 1],
	('minecraft:reserved6', 0) : ['tile.reserved6.name', 1],
	('minecraft:torchflower_crop', 0) : ['tile.torchflower_crop.name', 1],
	('minecraft:wall_banner', 0) : ['tile.wall_banner.name', 1],
	('minecraft:lit_redstone_lamp', 0) : ['tile.lit_redstone_lamp.name', 1],
	('minecraft:item.acacia_door', 0) : ['tile.acacia_door.name', 1],
	('minecraft:mangrove_standing_sign', 0) : ['tile.mangrove_standing_sign.name', 1],
	('minecraft:item.wooden_door', 0) : ['tile.wooden_door.name', 1],
	('minecraft:double_cut_copper_slab', 0) : ['tile.double_cut_copper_slab.name', 1],
	('minecraft:double_wooden_slab', 0) : ['tile.double_wooden_slab.oak.name', 1],
	('minecraft:powered_comparator', 0) : ['tile.powered_comparator.name', 1],
	('minecraft:glowingobsidian', 0) : ['tile.glowingobsidian.name', 1],
	('minecraft:oxidized_double_cut_copper_slab', 0) : ['tile.oxidized_double_cut_copper_slab.name', 1],
	('minecraft:exposed_double_cut_copper_slab', 0) : ['tile.exposed_double_cut_copper_slab.name', 1],
	('minecraft:polished_blackstone_double_slab', 0) : ['tile.polished_blackstone_double_slab.name', 1],
	('minecraft:hard_glass_pane', 0) : ['tile.hard_glass_pane.name', 1],
	('minecraft:end_gateway', 0) : ['tile.end_gateway.name', 1],
	('minecraft:mud_brick_double_slab', 0) : ['tile.mud_brick_double_slab.name', 1],
	('minecraft:info_update', 0) : ['tile.info_update.name', 1],
	('minecraft:pitcher_crop', 0) : ['tile.pitcher_crop.name', 1],
	('minecraft:item.flower_pot', 0) : ['tile.flower_pot.name', 1],
	('minecraft:blackstone_double_slab', 0) : ['tile.blackstone_double_slab.name', 1],
	('minecraft:element_110', 0) : ['tile.element.ds.name', 1],
	('minecraft:element_112', 0) : ['tile.element.cn.name', 1],
	('minecraft:element_114', 0) : ['tile.element.fl.name', 1],
	('minecraft:element_116', 0) : ['tile.element.lv.name', 1],
	('minecraft:element_117', 0) : ['tile.element.ts.name', 1],
	('minecraft:element_118', 0) : ['tile.element.og.name', 1],
	('minecraft:underwater_torch', 0) : ['tile.underwater_torch.name', 1],
	('minecraft:item.dark_oak_door', 0) : ['tile.dark_oak_door.name', 1],
	('minecraft:element_106', 0) : ['tile.element.sg.name', 1],
	('minecraft:element_107', 0) : ['tile.element.bh.name', 1],
	('minecraft:element_108', 0) : ['tile.element.hs.name', 1],
	('minecraft:element_51', 0) : ['tile.element.sb.name', 1],
	('minecraft:element_54', 0) : ['tile.element.xe.name', 1],
	('minecraft:element_57', 0) : ['tile.element.la.name', 1],
	('minecraft:element_59', 0) : ['tile.element.pr.name', 1],
	('minecraft:element_60', 0) : ['tile.element.nd.name', 1],
	('minecraft:element_61', 0) : ['tile.element.pm.name', 1],
	('minecraft:element_63', 0) : ['tile.element.eu.name', 1],
	('minecraft:element_65', 0) : ['tile.element.tb.name', 1],
	('minecraft:element_66', 0) : ['tile.element.dy.name', 1],
	('minecraft:element_67', 0) : ['tile.element.ho.name', 1],
	('minecraft:element_68', 0) : ['tile.element.er.name', 1],
	('minecraft:element_69', 0) : ['tile.element.tm.name', 1],
	('minecraft:element_70', 0) : ['tile.element.yb.name', 1],
	('minecraft:element_71', 0) : ['tile.element.lu.name', 1],
	('minecraft:element_72', 0) : ['tile.element.hf.name', 1],
	('minecraft:element_75', 0) : ['tile.element.re.name', 1],
	('minecraft:element_76', 0) : ['tile.element.os.name', 1],
	('minecraft:element_77', 0) : ['tile.element.ir.name', 1],
	('minecraft:element_78', 0) : ['tile.element.pt.name', 1],
	('minecraft:element_79', 0) : ['tile.element.au.name', 1],
	('minecraft:element_80', 0) : ['tile.element.hg.name', 1],
	('minecraft:element_81', 0) : ['tile.element.tl.name', 1],
	('minecraft:element_84', 0) : ['tile.element.po.name', 1],
	('minecraft:jungle_wall_sign', 0) : ['tile.jungle_wall_sign.name', 1],
	('minecraft:element_85', 0) : ['tile.element.at.name', 1],
	('minecraft:element_86', 0) : ['tile.element.rn.name', 1],
	('minecraft:element_87', 0) : ['tile.element.fr.name', 1],
	('minecraft:element_88', 0) : ['tile.element.ra.name', 1],
	('minecraft:element_90', 0) : ['tile.element.th.name', 1],
	('minecraft:element_91', 0) : ['tile.element.pa.name', 1],
	('minecraft:element_92', 0) : ['tile.element.u.name', 1],
	('minecraft:element_94', 0) : ['tile.element.pu.name', 1],
	('minecraft:element_97', 0) : ['tile.element.bk.name', 1],
	('minecraft:element_98', 0) : ['tile.element.cf.name', 1],
	('minecraft:element_100', 0) : ['tile.element.fm.name', 1],
	('minecraft:element_101', 0) : ['tile.element.md.name', 1],
	('minecraft:element_103', 0) : ['tile.element.lr.name', 1],
	('minecraft:element_105', 0) : ['tile.element.db.name', 1],
	('minecraft:mod_ore', 0) : ['tile.mod_ore.0.name', 1],
	('minecraft:element_95', 0) : ['tile.element.am.name', 1],
	('minecraft:element_0', 0) : ['tile.element.unknown.name', 1],
	('minecraft:element_2', 0) : ['tile.element.he.name', 1],
	('minecraft:element_4', 0) : ['tile.element.be.name', 1],
	('minecraft:element_5', 0) : ['tile.element.b.name', 1],
	('minecraft:element_6', 0) : ['tile.element.c.name', 1],
	('minecraft:element_8', 0) : ['tile.element.o.name', 1],
	('minecraft:element_9', 0) : ['tile.element.f.name', 1],
	('minecraft:lit_blast_furnace', 0) : ['tile.lit_blast_furnace.name', 1],
	('minecraft:element_11', 0) : ['tile.element.na.name', 1],
	('minecraft:element_12', 0) : ['tile.element.mg.name', 1],
	('minecraft:element_13', 0) : ['tile.element.al.name', 1],
	('minecraft:element_14', 0) : ['tile.element.si.name', 1],
	('minecraft:element_16', 0) : ['tile.element.s.name', 1],
	('minecraft:element_17', 0) : ['tile.element.cl.name', 1],
	('minecraft:element_20', 0) : ['tile.element.ca.name', 1],
	('minecraft:element_21', 0) : ['tile.element.sc.name', 1],
	('minecraft:element_22', 0) : ['tile.element.ti.name', 1],
	('minecraft:element_23', 0) : ['tile.element.v.name', 1],
	('minecraft:element_24', 0) : ['tile.element.cr.name', 1],
	('minecraft:element_26', 0) : ['tile.element.fe.name', 1],
	('minecraft:element_27', 0) : ['tile.element.co.name', 1],
	('minecraft:element_28', 0) : ['tile.element.ni.name', 1],
	('minecraft:element_29', 0) : ['tile.element.cu.name', 1],
	('minecraft:element_30', 0) : ['tile.element.zn.name', 1],
	('minecraft:element_31', 0) : ['tile.element.ga.name', 1],
	('minecraft:element_32', 0) : ['tile.element.ge.name', 1],
	('minecraft:element_33', 0) : ['tile.element.as.name', 1],
	('minecraft:element_35', 0) : ['tile.element.br.name', 1],
	('minecraft:element_36', 0) : ['tile.element.kr.name', 1],
	('minecraft:element_37', 0) : ['tile.element.rb.name', 1],
	('minecraft:element_39', 0) : ['tile.element.y.name', 1],
	('minecraft:element_40', 0) : ['tile.element.zr.name', 1],
	('minecraft:element_41', 0) : ['tile.element.nb.name', 1],
	('minecraft:element_42', 0) : ['tile.element.mo.name', 1],
	('minecraft:element_45', 0) : ['tile.element.rh.name', 1],
	('minecraft:element_48', 0) : ['tile.element.cd.name', 1],
	('minecraft:element_49', 0) : ['tile.element.in.name', 1],
	('minecraft:element_50', 0) : ['tile.element.sn.name', 1],
	('minecraft:hard_stained_glass', 0) : ['tile.hard_stained_glass.white.name', 1],
	('minecraft:hard_stained_glass_pane', 0) : ['tile.hard_stained_glass_pane.white.name', 1],
	('minecraft:colored_torch_rg', 0) : ['tile.colored_torch.red.name', 1],
	('minecraft:item.glow_frame', 0) : ['tile.glow_frame.name', 1],
	('minecraft:element_83', 0) : ['tile.element.bi.name', 1],
	('minecraft:element_82', 0) : ['tile.element.pb.name', 1],
	('minecraft:double_stone_block_slab4', 0) : ['tile.double_stone_slab4.mossy_stone_brick.name', 1],
	('minecraft:element_10', 0) : ['tile.element.ne.name', 1],
	('minecraft:bamboo_double_slab', 0) : ['tile.bamboo_double_slab.name', 1],
	('minecraft:element_18', 0) : ['tile.element.ar.name', 1],
	('minecraft:element_62', 0) : ['tile.element.sm.name', 1],
	('minecraft:element_1', 0) : ['tile.element.h.name', 1],
	('minecraft:element_74', 0) : ['tile.element.w.name', 1],
	('minecraft:wall_sign', 0) : ['tile.wall_sign.name', 1],
	('minecraft:element_7', 0) : ['tile.element.n.name', 1],
	('minecraft:element_111', 0) : ['tile.element.rg.name', 1],
	('minecraft:element_64', 0) : ['tile.element.gd.name', 1],
	('minecraft:acacia_wall_sign', 0) : ['tile.acacia_wall_sign.name', 1],
	('minecraft:element_47', 0) : ['tile.element.ag.name', 1],
	('minecraft:element_73', 0) : ['tile.element.ta.name', 1],
	('minecraft:waxed_double_cut_copper_slab', 0) : ['tile.waxed_double_cut_copper_slab.name', 1],
	('minecraft:element_44', 0) : ['tile.element.ru.name', 1],
	('minecraft:powered_repeater', 0) : ['tile.powered_repeater.name', 1],
	('minecraft:daylight_detector_inverted', 0) : ['tile.daylight_detector_inverted.name', 1],
	('minecraft:element_115', 0) : ['tile.element.mc.name', 1],
	('minecraft:element_96', 0) : ['tile.element.cm.name', 1],
	('minecraft:mangrove_double_slab', 0) : ['tile.mangrove_double_slab.name', 1],
	('minecraft:element_3', 0) : ['tile.element.li.name', 1],
	('minecraft:element_109', 0) : ['tile.element.mt.name', 1],
	('minecraft:element_19', 0) : ['tile.element.k.name', 1],
	('minecraft:element_38', 0) : ['tile.element.sr.name', 1],
	('minecraft:bamboo_mosaic_double_slab', 0) : ['tile.bamboo_mosaic_double_slab.name', 1],
	('minecraft:element_58', 0) : ['tile.element.ce.name', 1],
	('minecraft:element_46', 0) : ['tile.element.pd.name', 1],
	('minecraft:polished_blackstone_brick_double_slab', 0) : ['tile.polished_blackstone_brick_double_slab.name', 1],
	('minecraft:element_104', 0) : ['tile.element.rf.name', 1],
	('minecraft:piston_arm_collision', 0) : ['tile.piston_arm_collision.name', 1],
	('minecraft:element_93', 0) : ['tile.element.np.name', 1],
	('minecraft:colored_torch_bp', 0) : ['tile.colored_torch.blue.name', 1],
	('minecraft:weathered_double_cut_copper_slab', 0) : ['tile.weathered_double_cut_copper_slab.name', 1],
	('minecraft:item.birch_door', 0) : ['tile.birch_door.name', 1],
	('minecraft:element_34', 0) : ['tile.element.se.name', 1],
	('minecraft:element_15', 0) : ['tile.element.p.name', 1],
	('minecraft:element_53', 0) : ['tile.element.i.name', 1],
	('minecraft:element_56', 0) : ['tile.element.ba.name', 1],
	('minecraft:element_102', 0) : ['tile.element.no.name', 1],
	('minecraft:client_request_placeholder_block', 0) : ['tile.client_request_placeholder_block.name', 1],
	('minecraft:element_25', 0) : ['tile.element.mn.name', 1],
	('minecraft:spruce_wall_sign', 0) : ['tile.spruce_wall_sign.name', 1],
	('minecraft:waxed_oxidized_double_cut_copper_slab', 0) : ['tile.waxed_oxidized_double_cut_copper_slab.name', 1],
	('minecraft:element_99', 0) : ['tile.element.es.name', 1],
	('minecraft:element_113', 0) : ['tile.element.nh.name', 1],
	('minecraft:lit_redstone_ore', 0) : ['tile.lit_redstone_ore.name', 1],
	('minecraft:bamboo_wall_sign', 0) : ['tile.bamboo_wall_sign.name', 1],
	('minecraft:item.frame', 0) : ['tile.frame.name', 1],
	('minecraft:lit_furnace', 0) : ['tile.lit_furnace.name', 1],
	('minecraft:element_43', 0) : ['tile.element.tc.name', 1],
	('minecraft:element_52', 0) : ['tile.element.te.name', 1],
	('minecraft:info_update2', 0) : ['tile.info_update2.name', 1],
	('minecraft:element_89', 0) : ['tile.element.ac.name', 1],
	('minecraft:end_portal', 0) : ['tile.end_portal.name', 1],
	('minecraft:element_55', 0) : ['tile.element.cs.name', 1],
	('minecraft:item.jungle_door', 0) : ['tile.jungle_door.name', 1],
	('minecraft:double_stone_block_slab3', 0) : ['tile.double_stone_slab3.end_brick.name', 1],
	('minecraft:chemistry_table', 0) : ['tile.compoundcreator.name', 1],

	('minecraft:double_stone_block_slab2', 0) : ['红砂岩台阶', 8],
	('minecraft:command_block', 0) : ['命令块', 6],
	('minecraft:coral_fan_hang', 0) : ['', 1],
	('minecraft:unknown', 0) : ['未知', 1],
	('minecraft:mod_ex', 0) : ['item.mod_ex.name', 1],
	('minecraft:lodestone_compass', 0) : ['磁石指南针', 1088],
	('minecraft:written_book', 0) : ['成书', 160],
	('minecraft:mod_armor', 0) : ['item.mod_armor.name', 1],
	('minecraft:command_block_minecart', 0) : ['命令方块矿车', 6],
	('minecraft:flowing_lava', 0) : ['岩浆', 64],
	('minecraft:cave_vines_body_with_berries', 0) : ['洞穴藤蔓', 8],
	('minecraft:pearlescent_froglight', 0) : ['珠光蛙明灯', 266],
	('minecraft:cobbled_deepslate_double_slab', 0) : ['深板岩圆石双台阶', 4],
	('minecraft:repeating_command_block', 0) : ['重复命令块', 6],
	('minecraft:double_stone_block_slab', 0) : ['石台阶', 1],
	('minecraft:trip_wire', 0) : ['绊线', 34],
	('minecraft:cave_vines_head_with_berries', 0) : ['洞穴藤蔓', 8],
	('minecraft:concrete', 0) : ['白色混凝土', 4],
	('minecraft:frosted_ice', 0) : ['冰霜', 6],
	('minecraft:debug_stick', 0) : ['item.debug_stick.name', 1],
	('minecraft:camera', 0) : ['摄像机', 1],
	('minecraft:compound', 0) : ['item.compound.salt.name', 1],
	('minecraft:ice_bomb', 0) : ['item.ice_bomb.name', 1],
	('minecraft:bleach', 0) : ['item.bleach.name', 1],
	('minecraft:rapid_fertilizer', 0) : ['item.rapid_fertilizer.name', 1],
	('minecraft:balloon', 0) : ['item.balloon.white.name', 1],
	('minecraft:medicine', 0) : ['item.medicine.blindness.name', 1],
	('minecraft:sparkler', 0) : ['item.sparkler.black.name', 1],
	('minecraft:powder_snow', 0) : ['细雪', 1],
	('minecraft:item.nether_wart', 0) : ['下界疣', 24],
	('minecraft:music_disc_relic', 0) : ['音乐唱片', 2048],
	('minecraft:stone', 0) : ['石头', 1],
	('minecraft:log', 0) : ['橡树原木', 32],
	('minecraft:spawn_egg', 0) : ['item.spawn_egg.name', 1],
	('minecraft:standing_sign', 0) : ['告示牌', 17],
	('minecraft:item.wheat', 0) : ['农作物', 6],
	('minecraft:magenta_concrete', 0) : ['品红色混凝土', 3],
	('minecraft:bubble_coral', 0) : ['气泡珊瑚', 6],
	('minecraft:coral', 0) : ['管珊瑚', 8],
	('minecraft:log2', 0) : ['金合欢原木', 32],
	('minecraft:dye', 0) : ['墨囊', 16],
	('minecraft:netherreactor', 0) : ['下界反应核', 666],
	('minecraft:item.nether_sprouts', 0) : ['下界苗', 1],
	('minecraft:item.cauldron', 0) : ['炼药锅', 1],
	('minecraft:micro_block', 0) : ['item.micro_block.name', 1],
	('minecraft:light_block', 0) : ['光明方块', 1],
	('minecraft:deepslate_tile_double_slab', 0) : ['深板岩瓦双台阶', 4],
	('minecraft:pumpkin_stem', 0) : ['南瓜梗', 1],
	('minecraft:suspicious_sand', 0) : ['可疑的沙子', 1],
	('minecraft:birch_standing_sign', 0) : ['白桦木告示牌', 17],
	('minecraft:item.warped_door', 0) : ['诡异门', 16],

	('minecraft:spruce_standing_sign', 0) : ['云杉木告示牌', 16],
	('minecraft:crimson_wall_sign', 0) : ['绯红木告示牌', 16],
	('minecraft:sculk_shrieker', 0) : ['幽匿尖啸体', 32160],
	('minecraft:potatoes', 0) : ['马铃薯', 64],
	('minecraft:mangrove_log', 0) : ['红树林原木', 32],
	('minecraft:pink_petals', 0) : ['粉红色花瓣', 4],
	('minecraft:soul_fire', 0) : ['灵魂火', 1],
	('minecraft:darkoak_standing_sign', 0) : ['深色橡木告示牌', 16],
	('minecraft:polished_deepslate_double_slab', 0) : ['磨制深板岩双台阶', 4],
	('minecraft:unlit_redstone_torch', 0) : ['红石火把', 68],
	('minecraft:stonecutter', 0) : ['切石机', 259],
	('minecraft:invisible_bedrock', 0) : ['隐形基岩', 1],
	('minecraft:deepslate_brick_double_slab', 0) : ['深板岩砖双台阶', 4],
	('minecraft:ochre_froglight', 0) : ['赭黄蛙明灯', 266],
	('minecraft:stripped_bamboo_block', 0) : ['去皮竹块', 288],
	('minecraft:pitcher_plant', 0) : ['猪笼草', 32],
	('minecraft:item.cake', 0) : ['蛋糕', 2450],
	('minecraft:redstone_wire', 0) : ['红石粉', 64],
	('minecraft:lava', 0) : ['岩浆', 1],
	('minecraft:item.crimson_door', 0) : ['绯红木门', 16],
	('minecraft:carrots', 0) : ['胡萝卜', 64],
	('minecraft:coral_fan_hang2', 0) : ['', 1],
	('minecraft:coral_fan_hang3', 0) : ['', 1],
	('minecraft:structure_void', 0) : ['结构空位', 1],
	('minecraft:sculk_sensor', 0) : ['幽匿感测体', 2680],
	('minecraft:stripped_cherry_log', 0) : ['去皮樱花原木', 32],
	('minecraft:item.iron_door', 0) : ['铁门', 512],

	('minecraft:border_block', 0) : ['边框', 1],
	('minecraft:suspicious_gravel', 0) : ['可疑砂砾', 4],
	('minecraft:flowing_water', 0) : ['水', 1],
	('minecraft:cave_vines', 0) : ['洞穴藤蔓', 8],
	('minecraft:jigsaw', 0) : ['线锯方块', 1],
	('minecraft:item.beetroot', 0) : ['甜菜根', 64],
	('minecraft:water', 0) : ['水', 1],
	('minecraft:deny', 0) : ['拒绝', 1],
	('minecraft:cherry_sapling', 0) : ['樱花树苗', 32],
	('minecraft:item.campfire', 0) : ['营火', 236],
	('minecraft:reinforced_deepslate', 0) : ['强化深板岩', 32],

	('minecraft:sweet_berry_bush', 0) : ['甜浆果灌木丛', 32],
	('minecraft:barrier', 0) : ['屏障', 1],
	('minecraft:item.brewing_stand', 0) : ['酿造台', 1539],
	('minecraft:jungle_standing_sign', 0) : ['丛林告示牌', 17],
	('minecraft:cherry_double_slab', 0) : ['樱花木双台阶', 4],
	('minecraft:item.camera', 0) : ['摄像机', 1],
	('minecraft:fire', 0) : ['火', 1],
	('minecraft:acacia_standing_sign', 0) : ['金合欢木告示牌', 17],
	('minecraft:structure_block', 0) : ['结构方块', 1],
	('minecraft:verdant_froglight', 0) : ['青翠蛙明灯', 266],
	('minecraft:cocoa', 0) : ['可可', 1],
	('minecraft:chain_command_block', 0) : ['链命令块', 1],
	('minecraft:mud', 0) : ['泥巴', 1],
	('minecraft:item.bed', 0) : ['床', 168],
	('minecraft:item.hopper', 0) : ['漏斗', 1344],
	('minecraft:allow', 0) : ['允许', 1],
	('minecraft:item.chain', 0) : ['链', 312],
	('minecraft:sculk_vein', 0) : ['幽匿脉络', 4],
	('minecraft:warped_standing_sign', 0) : ['诡异告示牌', 17],
	('minecraft:cherry_log', 0) : ['樱花原木', 32],
	('minecraft:crimson_standing_sign', 0) : ['绯红木告示牌', 16],
	('minecraft:portal', 0) : ['传送门', 8],
	('minecraft:stripped_mangrove_log', 0) : ['去皮红树林原木', 32],
}

# region 多个aux的相同物品EMC
_ItemsVariantAuxEMC = {
	('minecraft:torch', 0): ['火把', 8],
	('minecraft:torch', 1): ['火把', 8],
	('minecraft:torch', 2): ['火把', 8],
	('minecraft:torch', 3): ['火把', 8],
	('minecraft:torch', 4): ['火把', 8],

	('minecraft:stone', 0): ['石头', 1],
	('minecraft:stone', 1): ['花岗岩', 1],
	('minecraft:stone', 2): ['磨制花岗岩', 1],
	('minecraft:stone', 3): ['闪长岩', 1],
	('minecraft:stone', 4): ['磨制闪长岩', 1],
	('minecraft:stone', 5): ['安山岩', 1],
	('minecraft:stone', 6): ['磨制安山岩', 1],

	('minecraft:amethyst_cluster', 1): ['紫水晶簇', 32768],
	('minecraft:anvil', 4): ['轻微损坏的铁砧', 5290],
	('minecraft:anvil', 8): ['严重损坏的铁砧', 2645],
	('minecraft:arrow', 6): ['夜视箭', 220],
	('minecraft:arrow', 7): ['夜视箭', 600],
	('minecraft:arrow', 8): ['隐身箭', 220],
	('minecraft:arrow', 9): ['隐身箭', 600],
	('minecraft:arrow', 10): ['跳跃箭', 110],
	('minecraft:arrow', 11): ['跳跃箭', 220],
	('minecraft:arrow', 12): ['跳跃箭', 600],
	('minecraft:arrow', 13): ['抗火箭', 220],
	('minecraft:arrow', 14): ['抗火箭', 600],
	('minecraft:arrow', 15): ['迅捷之箭', 110],
	('minecraft:arrow', 16): ['迅捷之箭', 220],
	('minecraft:arrow', 17): ['迅捷之箭', 600],
	('minecraft:arrow', 18): ['缓慢之箭', 220],
	('minecraft:arrow', 19): ['缓慢之箭', 600],
	('minecraft:arrow', 20): ['水肺之箭', 220],
	('minecraft:arrow', 21): ['水肺之箭', 600],
	('minecraft:arrow', 22): ['治疗之箭', 220],
	('minecraft:arrow', 23): ['治疗之箭', 600],
	('minecraft:arrow', 24): ['伤害之箭', 220],
	('minecraft:arrow', 25): ['伤害之箭', 600],
	('minecraft:arrow', 26): ['剧毒箭', 110],
	('minecraft:arrow', 27): ['剧毒箭', 220],
	('minecraft:arrow', 28): ['剧毒箭', 600],
	('minecraft:arrow', 29): ['生命恢复之箭', 110],
	('minecraft:arrow', 30): ['生命恢复之箭', 220],
	('minecraft:arrow', 31): ['生命恢复之箭', 600],
	('minecraft:arrow', 32): ['力量箭', 110],
	('minecraft:arrow', 33): ['力量箭', 220],
	('minecraft:arrow', 34): ['力量箭', 600],
	('minecraft:arrow', 35): ['虚弱之箭', 220],
	('minecraft:arrow', 36): ['虚弱之箭', 600],
	('minecraft:arrow', 37): ['衰变之箭', 666],
	('minecraft:arrow', 38): ['神龟之箭', 200],
	('minecraft:arrow', 39): ['神龟之箭', 300],
	('minecraft:arrow', 40): ['神龟之箭', 500],
	('minecraft:arrow', 41): ['缓降之箭', 200],
	('minecraft:arrow', 42): ['缓降之箭', 300],
	('minecraft:arrow', 43): ['缓慢之箭', 500],
	('minecraft:banner', 1): ['红色旗帜', 292],
	('minecraft:banner', 2): ['绿色旗帜', 292],
	('minecraft:banner', 3): ['棕色旗帜', 292],
	('minecraft:banner', 4): ['蓝色旗帜', 292],
	('minecraft:banner', 5): ['紫色旗帜', 292],
	('minecraft:banner', 6): ['青色旗帜', 292],
	('minecraft:banner', 7): ['淡灰色旗帜', 292],
	('minecraft:banner', 8): ['灰色旗帜', 292],
	('minecraft:banner', 9): ['粉红色旗帜', 292],
	('minecraft:banner', 10): ['黄绿色旗帜', 292],
	('minecraft:banner', 11): ['黄色旗帜', 292],
	('minecraft:banner', 12): ['淡蓝色旗帜', 292],
	('minecraft:banner', 13): ['品红色旗帜', 292],
	('minecraft:banner', 14): ['橙色旗帜', 292],
	('minecraft:banner', 15): ['白色旗帜', 292],
	('minecraft:bed', 1): ['橙床', 168],
	('minecraft:bed', 2): ['品红床', 168],
	('minecraft:bed', 3): ['淡蓝床', 168],
	('minecraft:bed', 4): ['黄床', 168],
	('minecraft:bed', 5): ['黄绿床', 168],
	('minecraft:bed', 6): ['粉床', 168],
	('minecraft:bed', 7): ['灰床', 168],
	('minecraft:bed', 8): ['淡灰床', 168],
	('minecraft:bed', 9): ['青床', 168],
	('minecraft:bed', 10): ['紫床', 168],
	('minecraft:bed', 11): ['蓝床', 168],
	('minecraft:bed', 12): ['棕床', 168],
	('minecraft:bed', 13): ['绿床', 168],
	('minecraft:bed', 14): ['红床', 168],
	('minecraft:bed', 15): ['黑床', 168],
	('minecraft:big_dripleaf', 4): ['大型垂滴叶', 32],
	('minecraft:brown_mushroom_block', 14): ['棕色蘑菇方块', 32],
	('minecraft:brown_mushroom_block', 15): ['蘑菇柄', 32],
	('minecraft:cobblestone_wall', 1): ['苔石墙', 1],
	('minecraft:cobblestone_wall', 2): ['花岗岩墙', 1],
	('minecraft:cobblestone_wall', 3): ['闪长岩墙', 1],
	('minecraft:cobblestone_wall', 4): ['安山岩墙', 1],
	('minecraft:cobblestone_wall', 5): ['沙石墙', 1],
	('minecraft:cobblestone_wall', 6): ['砖墙', 1],
	('minecraft:cobblestone_wall', 7): ['石砖墙', 1],
	('minecraft:cobblestone_wall', 8): ['苔石砖墙', 1],
	('minecraft:cobblestone_wall', 9): ['下界砖墙', 1],
	('minecraft:cobblestone_wall', 10): ['末地石砖墙', 1],
	('minecraft:cobblestone_wall', 12): ['红沙石墙', 1],
	('minecraft:cobblestone_wall', 13): ['红色下界砖墙', 1],
	('minecraft:coral_block', 1): ['脑纹珊瑚块', 8],
	('minecraft:coral_block', 2): ['气泡珊瑚块', 8],
	('minecraft:coral_block', 3): ['火珊瑚块', 8],
	('minecraft:coral_block', 4): ['鹿角珊瑚块', 8],
	('minecraft:coral_block', 8): ['死亡管珊瑚块', 8],
	('minecraft:coral_block', 9): ['死亡脑纹珊瑚块', 8],
	('minecraft:coral_block', 10): ['死亡气泡珊瑚块', 8],
	('minecraft:coral_block', 11): ['死亡火珊瑚块', 8],
	('minecraft:coral_block', 12): ['死亡鹿角珊瑚块', 8],
	('minecraft:coral_fan', 1): ['脑纹珊瑚扇', 16],
	('minecraft:coral_fan', 2): ['气泡珊瑚扇', 16],
	('minecraft:coral_fan', 3): ['火珊瑚扇', 16],
	('minecraft:coral_fan', 4): ['鹿角珊瑚扇', 16],
	('minecraft:coral_fan_dead', 1): ['死亡脑纹珊瑚扇', 8],
	('minecraft:coral_fan_dead', 2): ['死亡气泡珊瑚扇', 8],
	('minecraft:coral_fan_dead', 3): ['死亡火珊瑚扇', 8],
	('minecraft:coral_fan_dead', 4): ['死亡鹿角珊瑚扇', 8],
	('minecraft:dirt', 1): ['砂土', 1],
	('minecraft:dispenser', 3): ['发射器', 119],
	('minecraft:double_plant', 1): ['丁香', 32],
	('minecraft:double_plant', 2): ['高草丛', 32],
	('minecraft:double_plant', 3): ['大型蕨', 32],
	('minecraft:double_plant', 4): ['玫瑰丛', 32],
	('minecraft:double_plant', 5): ['牡丹', 32],
	('minecraft:dropper', 3): ['投掷器', 71],
	('minecraft:empty_map', 2): ['空的定位器地图', 1344],
	('minecraft:firework_star', 1): ['焰火之星', 192],
	('minecraft:firework_star', 2): ['焰火之星', 192],
	('minecraft:firework_star', 3): ['焰火之星', 192],
	('minecraft:firework_star', 4): ['焰火之星', 192],
	('minecraft:firework_star', 5): ['焰火之星', 192],
	('minecraft:firework_star', 6): ['焰火之星', 192],
	('minecraft:firework_star', 7): ['焰火之星', 192],
	('minecraft:firework_star', 8): ['焰火之星', 192],
	('minecraft:firework_star', 9): ['焰火之星', 192],
	('minecraft:firework_star', 10): ['焰火之星', 192],
	('minecraft:firework_star', 11): ['焰火之星', 192],
	('minecraft:firework_star', 12): ['焰火之星', 192],
	('minecraft:firework_star', 13): ['焰火之星', 192],
	('minecraft:firework_star', 14): ['焰火之星', 192],
	('minecraft:firework_star', 15): ['焰火之星', 192],
	('minecraft:glow_lichen', 63): ['发光地衣', 8],
	('minecraft:large_amethyst_bud', 1): ['大型紫水晶芽', 24576],
	('minecraft:leaves', 1): ['云杉叶', 1],
	('minecraft:leaves', 2): ['桦树叶', 1],
	('minecraft:leaves', 3): ['丛林树叶', 1],
	('minecraft:leaves2', 1): ['深色橡树叶', 1],
	('minecraft:lingering_potion', 1): ['滞留型平凡药水', 2701],
	('minecraft:lingering_potion', 2): ['滞留型长久平凡药水', 2706],
	('minecraft:lingering_potion', 3): ['滞留型浓稠药水', 2829],
	('minecraft:lingering_potion', 4): ['滞留型粗制药水', 2709],
	('minecraft:lingering_potion', 5): ['滞留型夜视药水', 3335],
	('minecraft:lingering_potion', 6): ['滞留型夜视药水', 3356],
	('minecraft:lingering_potion', 7): ['滞留型隐身药水', 3393],
	('minecraft:lingering_potion', 8): ['滞留型隐身药水', 3414],
	('minecraft:lingering_potion', 9): ['滞留型跳跃药水', 2751],
	('minecraft:lingering_potion', 10): ['滞留型跳跃药水', 2772],
	('minecraft:lingering_potion', 11): ['滞留型跳跃药水', 2879],
	('minecraft:lingering_potion', 12): ['滞留型抗火药水', 2975],
	('minecraft:lingering_potion', 13): ['滞留型抗火药水', 2996],
	('minecraft:lingering_potion', 14): ['滞留型迅捷药水', 2714],
	('minecraft:lingering_potion', 15): ['滞留型迅捷药水', 2735],
	('minecraft:lingering_potion', 16): ['滞留型迅捷药水', 2842],
	('minecraft:lingering_potion', 17): ['滞留型缓慢药水', 2772],
	('minecraft:lingering_potion', 18): ['滞留型缓慢药水', 2793],
	('minecraft:lingering_potion', 19): ['滞留型水肺药水', 2730],
	('minecraft:lingering_potion', 20): ['滞留型水肺药水', 2751],
	('minecraft:lingering_potion', 21): ['滞留型治疗药水', 3319],
	('minecraft:lingering_potion', 22): ['滞留型治疗药水', 3447],
	('minecraft:lingering_potion', 23): ['滞留型伤害药水', 2809],
	('minecraft:lingering_potion', 24): ['滞留型伤害药水', 2937],
	('minecraft:lingering_potion', 25): ['滞留型剧毒药水', 2751],
	('minecraft:lingering_potion', 26): ['滞留型剧毒药水', 2772],
	('minecraft:lingering_potion', 27): ['滞留型剧毒药水', 2879],
	('minecraft:lingering_potion', 28): ['滞留型生命恢复药水', 4074],
	('minecraft:lingering_potion', 29): ['滞留型生命恢复药水', 4095],
	('minecraft:lingering_potion', 30): ['滞留型生命恢复药水', 4202],
	('minecraft:lingering_potion', 31): ['滞留型力量药水', 2965],
	('minecraft:lingering_potion', 32): ['滞留型力量药水', 2986],
	('minecraft:lingering_potion', 33): ['滞留型力量药水', 3093],
	('minecraft:lingering_potion', 34): ['滞留型虚弱药水', 2759],
	('minecraft:lingering_potion', 35): ['滞留型虚弱药水', 2780],
	('minecraft:lingering_potion', 36): ['滞留型衰变药水', 2714],
	('minecraft:lingering_potion', 37): ['滞留型神龟药水', 2869],
	('minecraft:lingering_potion', 38): ['滞留型神龟药水', 2890],
	('minecraft:lingering_potion', 39): ['滞留型神龟药水', 2997],
	('minecraft:lingering_potion', 40): ['滞留型缓降药水', 2773],
	('minecraft:lingering_potion', 41): ['滞留型缓降药水', 2794],
	('minecraft:lingering_potion', 42): ['滞留型缓慢药水', 2900],
	('minecraft:medium_amethyst_bud', 1): ['中型紫晶芽', 16384],
	('minecraft:monster_egg', 1): ['被虫蚀的圆石', 8],
	('minecraft:monster_egg', 2): ['被虫蚀的石砖', 8],
	('minecraft:monster_egg', 3): ['被虫蚀的苔石砖', 8],
	('minecraft:monster_egg', 4): ['被虫蚀的裂石砖', 8],
	('minecraft:monster_egg', 5): ['被虫蚀的錾制石砖', 8],
	('minecraft:piston', 1): ['活塞', 348],
	('minecraft:spruce_planks', 0): ['云杉树木板', 8],
	('minecraft:birch_planks', 0): ['桦木板', 8],
	('minecraft:jungle_planks', 0): ['丛林树木板', 8],
	('minecraft:acacia_planks', 0): ['金合欢木板', 8],
	('minecraft:dark_oak_planks', 0): ['深色橡木木板', 8],
	('minecraft:pointed_dripstone', 8): ['滴水石锥', 32],
	('minecraft:potion', 1): ['平凡药水', 1],
	('minecraft:potion', 2): ['长久平凡药水', 6],
	('minecraft:potion', 3): ['浓稠药水', 129],
	('minecraft:potion', 4): ['粗制药水', 9],
	('minecraft:potion', 5): ['夜视药水', 635],
	('minecraft:potion', 6): ['夜视药水', 656],
	('minecraft:potion', 7): ['隐身药水', 693],
	('minecraft:potion', 8): ['隐身药水', 714],
	('minecraft:potion', 9): ['跳跃药水', 51],
	('minecraft:potion', 10): ['跳跃药水', 72],
	('minecraft:potion', 11): ['跳跃药水', 179],
	('minecraft:potion', 12): ['抗火药水', 275],
	('minecraft:potion', 13): ['抗火药水', 296],
	('minecraft:potion', 14): ['迅捷药水', 14],
	('minecraft:potion', 15): ['迅捷药水', 35],
	('minecraft:potion', 16): ['迅捷药水', 142],
	('minecraft:potion', 17): ['缓慢药水', 72],
	('minecraft:potion', 18): ['缓慢药水', 93],
	('minecraft:potion', 19): ['水肺药水', 30],
	('minecraft:potion', 20): ['水肺药水', 51],
	('minecraft:potion', 21): ['治疗药水', 619],
	('minecraft:potion', 22): ['治疗药水', 747],
	('minecraft:potion', 23): ['伤害药水', 109],
	('minecraft:potion', 24): ['伤害药水', 237],
	('minecraft:potion', 25): ['剧毒药水', 51],
	('minecraft:potion', 26): ['剧毒药水', 72],
	('minecraft:potion', 27): ['剧毒药水', 179],
	('minecraft:potion', 28): ['生命恢复药水', 1374],
	('minecraft:potion', 29): ['生命恢复药水', 1395],
	('minecraft:potion', 30): ['生命恢复药水', 1502],
	('minecraft:potion', 31): ['力量药水', 265],
	('minecraft:potion', 32): ['力量药水', 286],
	('minecraft:potion', 33): ['力量药水', 393],
	('minecraft:potion', 34): ['虚弱药水', 59],
	('minecraft:potion', 35): ['虚弱药水', 80],
	('minecraft:potion', 36): ['衰变药水', 14],
	('minecraft:potion', 37): ['神龟药水', 169],
	('minecraft:potion', 38): ['神龟药水', 190],
	('minecraft:potion', 39): ['神龟药水', 297],
	('minecraft:potion', 40): ['缓降药水', 73],
	('minecraft:potion', 41): ['缓降药水', 94],
	('minecraft:potion', 42): ['缓慢药水', 200],
	('minecraft:purpur_block', 2): ['紫珀柱子', 192],
	('minecraft:quartz_block', 1): ['錾制石英块', 1024],
	('minecraft:quartz_block', 2): ['竖纹石英块', 1024],
	('minecraft:quartz_block', 3): ['平滑石英块', 1024],
	('minecraft:red_flower', 1): ['兰花', 16],
	('minecraft:red_flower', 2): ['绒球葱', 16],
	('minecraft:red_flower', 3): ['茜草花', 16],
	('minecraft:red_flower', 4): ['红色郁金香', 16],
	('minecraft:red_flower', 5): ['橙色郁金香', 16],
	('minecraft:red_flower', 6): ['白色郁金香', 16],
	('minecraft:red_flower', 7): ['粉红色郁金香', 16],
	('minecraft:red_flower', 8): ['滨菊', 16],
	('minecraft:red_flower', 9): ['矢车菊', 16],
	('minecraft:red_flower', 10): ['铃兰', 16],
	('minecraft:red_mushroom_block', 14): ['红色蘑菇方块', 8],
	('minecraft:red_sandstone', 1): ['錾制红沙石', 4],
	('minecraft:red_sandstone', 2): ['切制红沙石', 4],
	('minecraft:red_sandstone', 3): ['平滑红沙石', 4],
	('minecraft:sand', 1): ['红沙', 1],
	('minecraft:sandstone', 1): ['錾制沙石', 4],
	('minecraft:sandstone', 2): ['切制沙石', 4],
	('minecraft:sandstone', 3): ['平滑沙石', 4],
	('minecraft:sapling', 1): ['云杉树苗', 32],
	('minecraft:sapling', 2): ['桦树苗', 32],
	('minecraft:sapling', 3): ['丛林树苗', 32],
	('minecraft:sapling', 4): ['金合欢树苗', 32],
	('minecraft:sapling', 5): ['深色橡树苗', 32],
	('minecraft:skull', 1): ['凋灵骷髅模型', 5024],
	('minecraft:skull', 2): ['僵尸模型', 5024],
	('minecraft:skull', 3): ['模型', 5024],
	('minecraft:skull', 4): ['爬行者的模型', 5024],
	('minecraft:skull', 5): ['龙的模型', 5024],
	('minecraft:small_amethyst_bud', 1): ['小型紫水晶芽', 8192],
	('minecraft:small_dripleaf_block', 7): ['小型垂滴叶', 24],
	('minecraft:splash_potion', 1): ['喷溅型平凡药水', 65],
	('minecraft:splash_potion', 2): ['喷溅型长久平凡药水', 70],
	('minecraft:splash_potion', 3): ['喷溅型浓稠药水', 193],
	('minecraft:splash_potion', 4): ['喷溅型粗制药水', 73],
	('minecraft:splash_potion', 5): ['喷溅型夜视药水', 699],
	('minecraft:splash_potion', 6): ['喷溅型夜视药水', 720],
	('minecraft:splash_potion', 7): ['喷溅型隐身药水', 757],
	('minecraft:splash_potion', 8): ['喷溅型隐身药水', 778],
	('minecraft:splash_potion', 9): ['喷溅型跳跃药水', 115],
	('minecraft:splash_potion', 10): ['喷溅型跳跃药水', 136],
	('minecraft:splash_potion', 11): ['喷溅型跳跃药水', 243],
	('minecraft:splash_potion', 12): ['喷溅型抗火药水', 339],
	('minecraft:splash_potion', 13): ['喷溅型抗火药水', 360],
	('minecraft:splash_potion', 14): ['喷溅型迅捷药水', 78],
	('minecraft:splash_potion', 15): ['喷溅型迅捷药水', 99],
	('minecraft:splash_potion', 16): ['喷溅型迅捷药水', 206],
	('minecraft:splash_potion', 17): ['喷溅型缓慢药水', 136],
	('minecraft:splash_potion', 18): ['喷溅型缓慢药水', 157],
	('minecraft:splash_potion', 19): ['喷溅型水肺药水', 94],
	('minecraft:splash_potion', 20): ['喷溅型水肺药水', 115],
	('minecraft:splash_potion', 21): ['喷溅型治疗药水', 683],
	('minecraft:splash_potion', 22): ['喷溅型治疗药水', 811],
	('minecraft:splash_potion', 23): ['喷溅型伤害药水', 173],
	('minecraft:splash_potion', 24): ['喷溅型伤害药水', 301],
	('minecraft:splash_potion', 25): ['喷溅型剧毒药水', 115],
	('minecraft:splash_potion', 26): ['喷溅型剧毒药水', 136],
	('minecraft:splash_potion', 27): ['喷溅型剧毒药水', 243],
	('minecraft:splash_potion', 28): ['喷溅型生命恢复药水', 1438],
	('minecraft:splash_potion', 29): ['喷溅型生命恢复药水', 1459],
	('minecraft:splash_potion', 30): ['喷溅型生命恢复药水', 1566],
	('minecraft:splash_potion', 31): ['喷溅型力量药水', 329],
	('minecraft:splash_potion', 32): ['喷溅型力量药水', 350],
	('minecraft:splash_potion', 33): ['喷溅型力量药水', 457],
	('minecraft:splash_potion', 34): ['喷溅型虚弱药水', 123],
	('minecraft:splash_potion', 35): ['喷溅型虚弱药水', 144],
	('minecraft:splash_potion', 36): ['喷溅型衰变药水', 78],
	('minecraft:splash_potion', 37): ['喷溅型神龟药水', 233],
	('minecraft:splash_potion', 38): ['喷溅型神龟药水', 254],
	('minecraft:splash_potion', 39): ['喷溅型神龟药水', 361],
	('minecraft:splash_potion', 40): ['喷溅型缓降药水', 137],
	('minecraft:splash_potion', 41): ['喷溅型缓降药水', 158],
	('minecraft:splash_potion', 42): ['喷溅型缓慢药水', 264],
	('minecraft:sponge', 1): ['湿海绵', 128],

	('minecraft:sticky_piston', 1): ['黏性活塞', 380],
	('minecraft:stonebrick', 1): ['苔石砖', 1],
	('minecraft:stonebrick', 2): ['裂石砖', 1],
	('minecraft:stonebrick', 3): ['錾制石砖', 1],
	('minecraft:tallgrass', 1): ['草', 1],
	('minecraft:tallgrass', 2): ['蕨', 1],
	('minecraft:wood', 1): ['云杉木', 42],
	('minecraft:wood', 2): ['桦木', 42],
	('minecraft:wood', 3): ['丛林木', 42],
	('minecraft:wood', 4): ['金合欢木', 42],
	('minecraft:wood', 5): ['深色橡木', 42],
	('minecraft:wood', 8): ['条形橡木', 42],
	('minecraft:wood', 9): ['条形云杉木', 42],
	('minecraft:wood', 10): ['条形桦木', 42],
	('minecraft:wood', 11): ['条形丛林木', 42],
	('minecraft:wood', 12): ['条形金合欢木', 42],
	('minecraft:wood', 13): ['条形深色橡木', 42],
	('minecraft:wooden_slab', 1): ['云杉木台阶', 4],
	('minecraft:wooden_slab', 2): ['桦木台阶', 4],
	('minecraft:wooden_slab', 3): ['丛林木台阶', 4],
	('minecraft:wooden_slab', 4): ['金合欢木台阶', 4],
	('minecraft:wooden_slab', 5): ['深色橡木台阶', 4],
	('minecraft:oak_log', 0): ['橡树原木', 32],
	('minecraft:spruce_log', 0): ['云杉原木', 32],
	('minecraft:birch_log', 0): ['桦树原木', 32],
	('minecraft:jungle_log', 0): ['丛林原木', 32],
	('minecraft:acacia_log', 0): ['金合欢原木', 32],
	('minecraft:dark_oak_log', 0): ['深色橡树原木', 32],
	('minecraft:oak_fence', 0): ['橡木围墙', 12],
	('minecraft:spruce_fence', 0): ['云杉围墙', 12],
	('minecraft:birch_fence', 0): ['桦木围墙', 12],
	('minecraft:jungle_fence', 0): ['丛林木围墙', 12],
	('minecraft:acacia_fence', 0): ['金合欢木围墙', 12],
	('minecraft:dark_oak_fence', 0): ['深色橡木围墙', 12],
	('minecraft:tube_coral', 0): ['管珊瑚', 16],
	('minecraft:brain_coral', 0): ['脑纹珊瑚', 16],
	('minecraft:bubble_coral', 0): ['气泡珊瑚', 16],
	('minecraft:fire_coral', 0): ['火珊瑚', 16],
	('minecraft:horn_coral', 0): ['鹿角珊瑚', 16],
	('minecraft:dead_tube_coral', 0): ['死亡管珊瑚', 16],
	('minecraft:dead_brain_coral', 0): ['死亡脑珊瑚', 16],
	('minecraft:dead_bubble_coral', 0): ['死亡泡珊瑚', 16],
	('minecraft:dead_fire_coral', 0): ['死亡火珊瑚', 16],
	('minecraft:dead_horn_coral', 0): ['死亡角珊瑚', 16],
	('minecraft:white_carpet', 0): ['白色地毯', 32],
	('minecraft:orange_carpet', 0): ['橙色地毯', 32],
	('minecraft:magenta_carpet', 0): ['品红色地毯', 32],
	('minecraft:light_blue_carpet', 0): ['淡蓝色地毯', 32],
	('minecraft:yellow_carpet', 0): ['黄色地毯', 32],
	('minecraft:lime_carpet', 0): ['黄绿色地毯', 32],
	('minecraft:pink_carpet', 0): ['粉红色地毯', 32],
	('minecraft:gray_carpet', 0): ['灰色地毯', 32],
	('minecraft:light_gray_carpet', 0): ['淡灰色地毯', 32],
	('minecraft:cyan_carpet', 0): ['青色地毯', 32],
	('minecraft:purple_carpet', 0): ['紫色地毯', 32],
	('minecraft:blue_carpet', 0): ['蓝色地毯', 32],
	('minecraft:brown_carpet', 0): ['棕色地毯', 32],
	('minecraft:green_carpet', 0): ['绿色地毯', 32],
	('minecraft:red_carpet', 0): ['红色地毯', 32],
	('minecraft:black_carpet', 0): ['黑色地毯', 32],

	# 1.20更新
	# 木板
	('minecraft:mangrove_planks', 0): ['红树林木板', 8],
	('minecraft:cherry_planks', 0): ['樱花木板', 8],
	('minecraft:bamboo_planks', 0): ['竹板', 8],
	('minecraft:bamboo_mosaic', 0): ['竹制马赛克', 8],
	# 栅栏
	('minecraft:oak_fence', 0): ['橡木栅栏', 13],
	('minecraft:crimson_fence', 0): ['绯红木栅栏', 13],
	('minecraft:warped_fence', 0): ['诡异木栅栏', 13],
	('minecraft:mangrove_fence', 0): ['红树林栅栏', 13],
	('minecraft:crimson_fence', 0): ['绯红木栅栏', 13],
	('minecraft:warped_fence', 0): ['诡异木栅栏', 13],
	('minecraft:mangrove_fence', 0): ['红树林栅栏', 13],
	('minecraft:cherry_fence', 0): ['樱花木栅栏', 13],
	('minecraft:bamboo_fence', 0): ['竹制栅栏', 13],
	('minecraft:mangrove_fence_gate', 0): ['红树林栅栏门', 32],
	('minecraft:cherry_fence_gate', 0): ['樱花木栅栏门', 32],
	('minecraft:bamboo_fence_gate', 0): ['竹制栅栏门', 32],
	# 门
	('minecraft:mangrove_door', 0): ['红树林门', 16],
	('minecraft:cherry_door', 0): ['樱花木门', 16],
	('minecraft:bamboo_door', 0): ['竹制楼门', 16],
	# 活板门
	('minecraft:mangrove_trapdoor', 0): ['红树林活板门', 24],
	('minecraft:cherry_trapdoor', 0): ['樱花木活板门', 24],
	('minecraft:bamboo_trapdoor', 0): ['竹制活板门', 24],
	# 墙
	('minecraft:cobblestone_wall', 1): ['苔石墙', 9],
	('minecraft:cobblestone_wall', 2): ['花岗岩墙', 16],
	('minecraft:cobblestone_wall', 3): ['闪长岩墙', 16],
	('minecraft:cobblestone_wall', 4): ['安山岩墙', 16],
	('minecraft:cobblestone_wall', 5): ['砂岩墙', 4],
	('minecraft:cobblestone_wall', 6): ['砖墙', 64],
	('minecraft:cobblestone_wall', 8): ['苔石砖墙', 9],
	('minecraft:cobblestone_wall', 9): ['下界砖墙', 4],
	('minecraft:cobblestone_wall', 11): ['海晶石墙', 1024],
	('minecraft:cobblestone_wall', 12): ['红砂岩墙', 4],
	('minecraft:cobblestone_wall', 13): ['红色下界砖墙', 50],
	('minecraft:deepslate_tile_wall', 0): ['深板岩圆石墙', 2],
	('minecraft:cobbled_deepslate_wall', 0): ['深板岩瓦墙', 2],
	# 楼梯
	('minecraft:mangrove_stairs', 0): ['红树林楼梯', 12],
	('minecraft:cherry_stairs', 0): ['樱花木楼梯', 12],
	('minecraft:bamboo_stairs', 0): ['竹制楼梯', 12],
	('minecraft:bamboo_mosaic_stairs', 0): ['竹制马赛克楼梯', 12],
	('minecraft:blackstone_stairs', 0): ['黑石楼梯', 4],
	('minecraft:polished_blackstone_brick_stairs', 0): ['磨制黑石砖块阶梯', 4],
	('minecraft:polished_blackstone_stairs', 0): ['磨制黑石楼梯', 4],
	('minecraft:cobbled_deepslate_stairs', 0): ['深板岩圆石楼梯', 2],
	('minecraft:polished_deepslate_stairs', 0): ['磨制深板岩楼梯', 2],
	('minecraft:deepslate_brick_stairs', 0): ['深板岩砖楼梯', 2],
	('minecraft:deepslate_tile_stairs', 0): ['深板岩瓦楼梯', 2],
	('minecraft:diorite_stairs', 0): ['闪长岩楼梯', 16],
	('minecraft:polished_diorite_stairs', 0): ['磨制闪长岩楼梯', 16],
	('minecraft:granite_stairs', 0): ['花岗岩楼梯', 16],
	('minecraft:polished_granite_stairs', 0): ['磨制花岗岩楼梯', 16],
	('minecraft:andesite_stairs', 0): ['安山岩楼梯', 16],
	('minecraft:polished_andesite_stairs', 0): ['磨制安山岩楼梯', 16],
	('minecraft:mossy_cobblestone_stairs', 0): ['苔圆石楼梯', 9],
	('minecraft:mossy_stone_brick_stairs', 0): ['苔石砖楼梯', 9],
	('minecraft:nether_brick_stairs', 0): ['下界砖楼梯', 4],
	('minecraft:red_nether_brick_stairs', 0): ['红色下界砖楼梯', 50],
	('minecraft:sandstone_stairs', 0): ['砂石楼梯', 4],
	('minecraft:smooth_sandstone_stairs', 0): ['平滑沙石楼梯', 4],
	('minecraft:red_sandstone_stairs', 0): ['红砂石楼梯', 4],
	('minecraft:smooth_red_sandstone_stairs', 0): ['平滑红砂石楼梯', 4],
	('minecraft:quartz_stairs', 0): ['石英楼梯', 1024],
	('minecraft:smooth_quartz_stairs', 0): ['平滑石英楼梯', 1024],
	('minecraft:purpur_stairs', 0): ['紫珀楼梯', 192],
	# 台阶
	('minecraft:double_stone_slab', 1): ['沙石台阶', 2],
	('minecraft:double_stone_slab', 3): ['圆石台阶', 1],
	('minecraft:double_stone_slab', 4): ['砖台阶', 32],
	('minecraft:double_stone_slab', 5): ['石砖台阶', 1],
	('minecraft:double_stone_slab', 6): ['石英台阶', 512],
	('minecraft:double_stone_slab', 7): ['下界砖台阶', 2],
	('minecraft:double_stone_slab2', 1): ['紫珀台阶', 96],
	('minecraft:double_stone_slab2', 2): ['海晶石台阶', 512],
	('minecraft:double_stone_slab2', 3): ['暗海晶石台阶', 1032],
	('minecraft:double_stone_slab2', 4): ['海晶石砖台阶', 1152],
	('minecraft:double_stone_slab2', 5): ['苔圆石台阶', 4],
	('minecraft:double_stone_slab2', 6): ['平滑沙石台阶', 2],
	('minecraft:double_stone_slab2', 7): ['红色下界砖台阶', 25],
	('minecraft:double_stone_slab3', 1): ['平滑红沙石台阶', 2],
	('minecraft:double_stone_slab3', 2): ['磨制安山岩台阶', 8],
	('minecraft:double_stone_slab3', 3): ['安山岩台阶', 8],
	('minecraft:double_stone_slab3', 4): ['闪长岩台阶', 8],
	('minecraft:double_stone_slab3', 5): ['磨制闪长岩台阶', 8],
	('minecraft:double_stone_slab3', 6): ['花岗岩台阶', 8],
	('minecraft:double_stone_slab3', 7): ['磨制花岗岩台阶', 8],
	('minecraft:double_stone_slab4', 1): ['平滑石英台阶', 512],
	('minecraft:double_stone_slab4', 2): ['石台阶', 1],
	('minecraft:double_stone_slab4', 3): ['切制沙石台阶', 2],
	('minecraft:double_stone_slab4', 4): ['切制红沙石台阶', 2],
	# 铜类
	('minecraft:raw_copper', 0): ['粗铜', 128],
	('minecraft:raw_copper_block', 0): ['粗铜块', 1152],
	('minecraft:copper_ore', 0): ['铜矿石', 128],
	('minecraft:deepslate_copper_ore', 0): ['深层铜矿石', 128],
	('minecraft:copper_ingot', 0): ['sd', 128],
	('minecraft:copper_block', 0): ['铜方块', 1152],
	('minecraft:exposed_copper', 0): ['斑驳的铜块', 1152],
	('minecraft:weathered_copper', 0): ['锈蚀的铜块', 1152],
	('minecraft:oxidized_copper', 0): ['氧化的铜块', 1152],
	('minecraft:cut_copper', 0): ['切制铜块', 288],
	('minecraft:exposed_cut_copper', 0): ['斑驳的切制铜块', 288],
	('minecraft:weathered_cut_copper', 0): ['锈蚀的切制铜块', 288],
	('minecraft:oxidized_cut_copper', 0): ['氧化的切制铜块', 288],
	('minecraft:waxed_copper', 0): ['涂蜡铜方块', 1168],
	('minecraft:waxed_exposed_copper', 0): ['斑驳的涂蜡铜块', 1168],
	('minecraft:waxed_weathered_copper', 0): ['锈蚀的涂蜡铜块', 1168],
	('minecraft:waxed_oxidized_copper', 0): ['氧化的涂蜡铜块', 1168],
	('minecraft:waxed_cut_copper', 0): ['涂蜡切制铜块', 292],
	('minecraft:waxed_exposed_cut_copper', 0): ['斑驳的涂蜡切制铜块', 292],
	('minecraft:waxed_weathered_cut_copper', 0): ['锈蚀的涂蜡切制铜块', 292],
	('minecraft:waxed_oxidized_cut_copper', 0): ['氧化的涂蜡切制铜块', 292],
	('minecraft:cut_copper_stairs', 0): ['切制铜块楼梯', 288],
	('minecraft:exposed_cut_copper_stairs', 0): ['斑驳的切制铜块楼梯', 288],
	('minecraft:weathered_cut_copper_stairs', 0): ['锈蚀切制铜块楼梯', 288],
	('minecraft:oxidized_cut_copper_stairs', 0): ['氧化切制铜块楼梯', 288],
	('minecraft:waxed_cut_copper_stairs', 0): ['涂蜡切制铜块楼梯', 292],
	('minecraft:waxed_exposed_cut_copper_stairs', 0): ['斑驳的涂蜡切制铜块楼梯', 292],
	('minecraft:waxed_weathered_cut_copper_stairs', 0): ['锈蚀涂蜡切制铜块楼梯', 292],
	('minecraft:waxed_oxidized_cut_copper_stairs', 0): ['氧化涂蜡切制铜块楼梯', 292],
	('minecraft:cut_copper_slab', 0): ['切制铜块台阶', 144],
	('minecraft:exposed_cut_copper_slab', 0): ['斑驳的切制铜块台阶', 144],
	('minecraft:weathered_cut_copper_slab', 0): ['锈蚀的切制铜台阶', 144],
	('minecraft:oxidized_cut_copper_slab', 0): ['氧化的切制铜块台阶', 144],
	('minecraft:waxed_cut_copper_slab', 0): ['涂蜡切制铜台阶', 146],
	('minecraft:waxed_exposed_cut_copper_slab', 0): ['斑驳的涂蜡切制铜块台阶', 146],
	('minecraft:waxed_weathered_cut_copper_slab', 0): ['锈蚀的涂蜡切制铜台阶', 146],
	('minecraft:waxed_oxidized_cut_copper_slab', 0): ['氧化的涂蜡切制铜台阶', 146],
	# 玻璃
	('minecraft:tinted_glass', 0): ['遮光玻璃', 64],
	('minecraft:stained_glass', 0): ['白色玻璃', 3],
	('minecraft:stained_glass', 1): ['橙色玻璃', 3],
	('minecraft:stained_glass', 2): ['品红色玻璃', 2],
	('minecraft:stained_glass', 3): ['淡蓝色玻璃', 3],
	('minecraft:stained_glass', 4): ['黄色玻璃', 3],
	('minecraft:stained_glass', 5): ['黄绿色玻璃', 2],
	('minecraft:stained_glass', 6): ['粉红色玻璃', 1],
	('minecraft:stained_glass', 7): ['灰色玻璃', 3],
	('minecraft:stained_glass', 8): ['淡灰色玻璃', 3],
	('minecraft:stained_glass', 9): ['青色玻璃', 2],
	('minecraft:stained_glass', 10): ['紫色玻璃', 3],
	('minecraft:stained_glass', 11): ['蓝色玻璃', 3],
	('minecraft:stained_glass', 12): ['棕色玻璃', 9],
	('minecraft:stained_glass', 13): ['绿色玻璃', 2],
	('minecraft:stained_glass', 14): ['红色玻璃', 3],
	('minecraft:stained_glass', 15): ['黑色玻璃', 3],
	('minecraft:stained_glass_pane', 0): ['白色玻璃板', 1],
	('minecraft:stained_glass_pane', 1): ['橙色玻璃板', 1],
	('minecraft:stained_glass_pane', 2): ['品红色玻璃板', 1],
	('minecraft:stained_glass_pane', 3): ['淡蓝色玻璃板', 1],
	('minecraft:stained_glass_pane', 4): ['黄色玻璃板', 1],
	('minecraft:stained_glass_pane', 5): ['黄绿色玻璃板', 1],
	('minecraft:stained_glass_pane', 6): ['粉红色玻璃板', 1],
	('minecraft:stained_glass_pane', 7): ['灰色玻璃板', 1],
	('minecraft:stained_glass_pane', 8): ['淡灰色玻璃板', 1],
	('minecraft:stained_glass_pane', 9): ['青色玻璃板', 1],
	('minecraft:stained_glass_pane', 10): ['紫色玻璃板', 1],
	('minecraft:stained_glass_pane', 11): ['蓝色玻璃板', 1],
	('minecraft:stained_glass_pane', 12): ['棕色玻璃板', 3],
	('minecraft:stained_glass_pane', 13): ['绿色玻璃板', 1],
	('minecraft:stained_glass_pane', 14): ['红色玻璃板', 1],
	('minecraft:stained_glass_pane', 15): ['黑色玻璃板', 1],
	# 海晶
	('minecraft:sea_lantern', 0): ['海晶灯', 3584],
	('minecraft:prismarine', 0): ['海晶石', 1024],
	('minecraft:prismarine_stairs', 0): ['海晶石楼梯', 1024],
	('minecraft:prismarine_crystals', 0): ['海晶砂粒', 512],
	('minecraft:prismarine_shard', 0): ['海晶碎片', 256],
	('minecraft:prismarine', 1): ['暗海晶石', 2064],
	('minecraft:prismarine', 2): ['海晶石砖', 1024],
	('minecraft:dark_prismarine_stairs', 0): ['暗海晶石楼梯', 2064],
	('minecraft:prismarine_bricks_stairs', 0): ['海晶石砖楼梯', 2304],
	# 陶瓦
	('minecraft:stained_hardened_clay', 1): ['橙色陶瓦', 66],
	('minecraft:stained_hardened_clay', 2): ['品红色陶瓦', 66],
	('minecraft:stained_hardened_clay', 3): ['淡蓝色陶瓦', 66],
	('minecraft:stained_hardened_clay', 4): ['黄色陶瓦', 66],
	('minecraft:stained_hardened_clay', 5): ['黄绿色陶瓦', 65],
	('minecraft:stained_hardened_clay', 6): ['粉红色陶瓦', 64],
	('minecraft:stained_hardened_clay', 7): ['灰色陶瓦', 66],
	('minecraft:stained_hardened_clay', 8): ['淡灰色陶瓦', 66],
	('minecraft:stained_hardened_clay', 9): ['青色陶瓦', 65],
	('minecraft:stained_hardened_clay', 10): ['紫色陶瓦', 66],
	('minecraft:stained_hardened_clay', 11): ['蓝色陶瓦', 66],
	('minecraft:stained_hardened_clay', 12): ['棕色陶瓦', 72],
	('minecraft:stained_hardened_clay', 13): ['绿色陶瓦', 65],
	('minecraft:stained_hardened_clay', 14): ['红色陶瓦', 66],
	('minecraft:stained_hardened_clay', 15): ['黑色陶瓦', 66],
	# 潜影盒
	('minecraft:undyed_shulker_box', 0): ['潜影盒', 4160],
	('minecraft:white_shulker_box', 0): ['白色潜影盒', 4176],
	('minecraft:orange_shulker_box', 0): ['橙色潜影盒', 4176],
	('minecraft:magenta_shulker_box', 0): ['品红色潜影盒', 4170],
	('minecraft:light_blue_shulker_box', 0): ['淡蓝色潜影盒', 4176],
	('minecraft:yellow_shulker_box', 0): ['黄色潜影盒', 4176],
	('minecraft:lime_shulker_box', 0): ['黄绿色潜影盒', 4172],
	('minecraft:pink_shulker_box', 0): ['粉红色潜影盒', 4164],
	('minecraft:gray_shulker_box', 0): ['灰色潜影盒', 4176],
	('minecraft:light_gray_shulker_box', 0): ['淡灰色潜影盒', 4176],
	('minecraft:cyan_shulker_box', 0): ['青色潜影盒', 4172],
	('minecraft:purple_shulker_box', 0): ['紫色潜影盒', 4176],
	('minecraft:blue_shulker_box', 0): ['蓝色潜影盒', 4176],
	('minecraft:brown_shulker_box', 0): ['棕色潜影盒', 4224],
	('minecraft:green_shulker_box', 0): ['绿色潜影盒', 4168],
	('minecraft:red_shulker_box', 0): ['红色潜影盒', 4176],
	('minecraft:black_shulker_box', 0): ['黑色潜影盒', 4176],
	# 混凝土
	('minecraft:white_concrete', 0): ['白色混凝土', 4],
	('minecraft:orange_concrete', 0): ['橙色混凝土', 4],
	('minecraft:magenta_concrete', 0): ['品红色混凝土', 3],
	('minecraft:light_blue_concrete', 0): ['淡蓝色混凝土', 4],
	('minecraft:yellow_concrete', 0): ['黄色混凝土', 4],
	('minecraft:lime_concrete', 0): ['黄绿色混凝土', 4],
	('minecraft:pink_concrete', 0): ['粉红色混凝土', 3],
	('minecraft:gray_concrete', 0): ['灰色混凝土', 4],
	('minecraft:light_gray_concrete', 0): ['淡灰色混凝土', 4],
	('minecraft:cyan_concrete', 0): ['青色混凝土', 4],
	('minecraft:purple_concrete', 0): ['紫色混凝土', 4],
	('minecraft:blue_concrete', 0): ['蓝色混凝土', 4],
	('minecraft:brown_concrete', 0): ['棕色混凝土', 10],
	('minecraft:green_concrete', 0): ['绿色混凝土', 3],
	('minecraft:red_concrete', 0): ['红色混凝土', 4],
	('minecraft:black_concrete', 0): ['黑色混凝土', 4],
	('minecraft:concrete_powder', 0): ['白色混凝土粉末', 4],
	('minecraft:concrete_powder', 1): ['橙色混凝土粉末', 4],
	('minecraft:concrete_powder', 2): ['品红色混凝土粉末', 3],
	('minecraft:concrete_powder', 3): ['淡蓝色混凝土粉末', 4],
	('minecraft:concrete_powder', 4): ['黄色混凝土粉末', 4],
	('minecraft:concrete_powder', 5): ['黄绿色混凝土粉末', 4],
	('minecraft:concrete_powder', 6): ['粉红色混凝土粉末', 3],
	('minecraft:concrete_powder', 7): ['灰色混凝土粉末', 4],
	('minecraft:concrete_powder', 8): ['淡灰色混凝土粉末', 4],
	('minecraft:concrete_powder', 9): ['青色混凝土粉末', 4],
	('minecraft:concrete_powder', 10): ['紫色混凝土粉末', 4],
	('minecraft:concrete_powder', 11): ['蓝色混凝土粉末', 4],
	('minecraft:concrete_powder', 12): ['棕色混凝土粉末', 10],
	('minecraft:concrete_powder', 13): ['绿色混凝土粉末', 3],
	('minecraft:concrete_powder', 14): ['红色混凝土粉末', 4],
	('minecraft:concrete_powder', 15): ['黑色混凝土粉末', 4],
	# 羊毛
	('minecraft:white_wool', 0): ['白色羊毛', 48],
	('minecraft:orange_wool', 0): ['橙色羊毛', 48],
	('minecraft:magenta_wool', 0): ['品红色羊毛', 48],
	('minecraft:light_blue_wool', 0): ['淡蓝色羊毛', 48],
	('minecraft:yellow_wool', 0): ['黄色羊毛', 48],
	('minecraft:lime_wool', 0): ['黄绿色羊毛', 48],
	('minecraft:pink_wool', 0): ['粉红色羊毛', 48],
	('minecraft:gray_wool', 0): ['灰色羊毛', 48],
	('minecraft:light_gray_wool', 0): ['淡灰色羊毛', 48],
	('minecraft:cyan_wool', 0): ['青色羊毛', 48],
	('minecraft:purple_wool', 0): ['紫色羊毛', 48],
	('minecraft:blue_wool', 0): ['蓝色羊毛', 48],
	('minecraft:brown_wool', 0): ['棕色羊毛', 48],
	('minecraft:green_wool', 0): ['绿色羊毛', 48],
	('minecraft:red_wool', 0): ['红色羊毛', 48],
	('minecraft:black_wool', 0): ['黑色羊毛', 48],
	#蜡烛
	('minecraft:magenta_candle', 0): ['品红色蜡烛', 44],
	('minecraft:brown_candle', 0): ['棕色蜡烛', 92],
	('minecraft:orange_candle', 0): ['橙色蜡烛', 44],
	('minecraft:light_gray_candle', 0): ['淡灰色蜡烛', 44],
	('minecraft:light_blue_candle', 0): ['淡蓝色蜡烛', 44],
	('minecraft:gray_candle', 0): ['灰色蜡烛', 44],
	('minecraft:white_candle', 0): ['白色蜡烛', 44],
	('minecraft:pink_candle', 0): ['粉红色蜡烛', 40],
	('minecraft:purple_candle', 0): ['紫色蜡烛', 44],
	('minecraft:red_candle', 0): ['红色蜡烛', 44],
	('minecraft:green_candle', 0): ['绿色蜡烛', 36],
	('minecraft:blue_candle', 0): ['蓝色蜡烛', 44],
	('minecraft:candle', 0): ['蜡烛', 28],
	('minecraft:cyan_candle', 0): ['青色蜡烛', 40],
	('minecraft:lime_candle', 0): ['黄绿色蜡烛', 44],
	('minecraft:yellow_candle', 0): ['黄色蜡烛', 44],
	('minecraft:black_candle', 0): ['黑色蜡烛', 44],
	# endregion
}


# region 其他模组物品EMC
"""这里一般是物品很少的模组，如拆解台只有一个物品"""
_ModItemsEMC = {
	('scuke_disassemble:disassemble_table', 0) : ['拆解台', 2752]
}
# endregion

# region 无价值的物品的id
_ItemsNoEMC = ["minecraft:air", "minecraft:debug_stick", ]
# endregion

# region 附魔值EMC
_EnchantEMC = {
	(0, 1) : ('ArmorAll', 2000),
	(1, 1) : ('ArmorFire', 2000),
	(2, 1) : ('ArmorFall', 2500),
	(3, 1) : ('ArmorExplosive', 2500),
	(4, 1) : ('ArmorProjectile', 2500),
	(5, 1) : ('ArmorThorns', 5000),
	(6, 1) : ('WaterBreath', 5000),
	(7, 1) : ('WaterSpeed', 5000),
	(8, 1) : ('WaterAffinity', 5000),
	(9, 1) : ('WeaponDamage', 6000),
	(10, 1) : ('WeaponUndead', 4000),
	(11, 1) : ('WeaponArthropod', 4000),
	(12, 1) : ('WeaponKnockback', 6000),
	(13, 1) : ('WeaponFire', 5000),
	(14, 1) : ('WeaponLoot', 4000),
	(15, 1) : ('MiningEfficiency', 5000),
	(16, 1) : ('MiningSilkTouch', 8000),
	(17, 1) : ('MiningDurability', 5000),
	(18, 1) : ('MiningLoot', 8000),
	(19, 1) : ('BowDamage', 6000),
	(20, 1) : ('BowKnockback', 4000),
	(21, 1) : ('BowFire', 7000),
	(22, 1) : ('BowInfinity', 9000),
	(23, 1) : ('FishingLoot', 5000),
	(24, 1) : ('FishingLure', 5000),
	(25, 1) : ('FrostWalker', 3000),
	(26, 1) : ('Mending', 40000),
	(27, 1) : ('CurseBinding', 1000),
	(28, 1) : ('CurseVanishing', 1000),
	(29, 1) : ('TridentImpaling', 3000),
	(30, 1) : ('TridentRiptide', 5000),
	(31, 1) : ('TridentLoyalty', 7000),
	(32, 1) : ('TridentChanneling', 7000),
	(33, 1) : ('CrossbowMultishot', 4000),
	(34, 1) : ('CrossbowPiercing', 5000),
	(35, 1) : ('CrossbowQuickCharge', 3000),
	(36, 1) : ('SoulSpeed', 2000),
	(37, 1) : ('SwiftSneak', 3500),
	(38, 1) : ('NumEnchantments', 1024),
	(39, 1) : ('InvalidEnchantment', 1024),
	(255, 1) : ('ModEnchant', 1024),
}


def GetEnchantEMC(key):
	return _EnchantEMC.get(key, ("未知", 0))
# endregion


# region 所有物品的EMC
_AllItemEmc = {}
_AllItemEmc.update(_ItemsEMC)
_AllItemEmc.update(_ModItemsEMC)
_AllItemEmc.update(_ItemsVariantAuxEMC)
# endregion


# region 设置某个物品的EMC值
def SetItemEMC(itemName,itemAux,itemPerEmc):
	"""
	设置某个物品的EMC值
	'''
	格式如下
	(物品Id,物品附加值Aux): [物品中文名, 物品单价]
	('minecraft:nether_star', 0): ['下界之星', 139264],
	'''
	"""
	key = (itemName,itemAux)
	if key in _AllItemEmc:
		emcValue = _AllItemEmc[key]
		_AllItemEmc[key] = [emcValue[0],itemPerEmc]
	else:
		print('========Set Item %s EMC Fail Not Find Item in Config========')
# endregion


# region 添加某个物品的EMC值
def AddItemEMC(itemName,itemAux,itemLangName,itemPerEmc):
	"""
	添加某个物品的EMC值到config
	'''
	格式如下
	(物品Id,物品附加值Aux): [物品本地化名, 物品单价]
	('minecraft:nether_star', 0): ['下界之星', 139264],
	'''
	"""
	key = (itemName,itemAux)
	if key not in _AllItemEmc:
		_AllItemEmc[key] = [itemLangName,itemPerEmc]
	else:
		print('========Add Item %s EMC Fail========')
# endregion


# region 获取某个物品的EMC单价
def GetItemEMC(itemName,itemAux):
	"""
	获取某个物品的EMC值
	"""
	key = (itemName,itemAux)
	if key in _AllItemEmc:
		return _AllItemEmc[key][1], True
	else:
		return 1, False
# endregion
