# -*- encoding: utf-8 -*-
class BuffEnum:
	"""buff类型枚举值"""

	Slowness = "scuke_survive:effect_slowness"
	"""生存减速"""
	HighTemp = "scuke_survive:effect_high_temp"
	"""高温状态"""
	LowTemp = "scuke_survive:effect_low_temp"
	"""低温状态"""
	HighRadiation = "scuke_survive:effect_high_radiation"
	"""高辐射状态"""
	GunDamage = "scuke_survive:effect_gun_damage"
	"""枪械增伤"""
	MeleeDamage = "scuke_survive:effect_melee_damage"
	"""近战增伤"""
	ColdResistance = "scuke_survive:effect_cold_resistance"
	"""抗寒度"""
	HotResistance = "scuke_survive:effect_hot_resistance"
	"""耐热度"""
	ScavengingRadiation = "scuke_survive:effect_scavenging_radiation"
	"""辐射消除"""
	ImmuneCold = "scuke_survive:effect_immune_cold"
	"""免疫冷(其他模组适配用)"""
	ImmuneHot = "scuke_survive:effect_immune_hot"
	"""免疫冷(其他模组适配用)"""

	EMP = "scuke_survive:effect_emp"
	"""电磁"""
	EnergyShield = "scuke_survive:effect_energy_shield"
	"""能量护盾"""
	EnergyShieldV2 = "scuke_survive:effect_energy_shield_v2"
	"""能量护盾V2"""
	EnergyShieldV3 = "scuke_survive:effect_energy_shield_v3"
	"""能量护盾V3"""
