# -*- coding: utf-8 -*-
from ScukeSurviveScript.modCommon.defines.monsterEnum import MonsterEnum

_MonsterPoolLv1 = {
    MonsterEnum.ZombieNormal: {"weight": 30, "count": 4},
    MonsterEnum.ZombieGangs: {"weight": 30, "count": 4},
    MonsterEnum.ZombieChick: {"weight": 30, "count": 4},
}

_MonsterPoolLv2 = {
    MonsterEnum.ZombieCaptain: {"weight": 30, "count": 3},
    MonsterEnum.ZombieDog: {"weight": 30, "count": 6},
    MonsterEnum.ZombieExplosive: {"weight": 30, "count": 4},
}

_MonsterPoolLv3 = {
    MonsterEnum.ZombieGuard: {"weight": 30, "count": 3},
    MonsterEnum.ZombieFat: {"weight": 30, "count": 4},
    MonsterEnum.ZombieGrandpa: {"weight": 30, "count": 5},
    MonsterEnum.ZombieSuperTNT: {"weight": 30, "count": 2},
}

_MonsterPoolLv4 = {
    MonsterEnum.ZombieOtaku: {"weight": 30, "count": 5},
    MonsterEnum.ZombieGangsCaptain: {"weight": 30, "count": 6},
    MonsterEnum.ZombieVenom: {"weight": 30, "count": 5},
    MonsterEnum.ZombieSpicyChick: {"weight": 30, "count": 7},
    MonsterEnum.ZombieTonsKing: {"weight": 30, "count": 4},
}

_MonsterPoolLv5 = {
    MonsterEnum.ZombieSpecialGuard: {"weight": 30, "count": 5},
    MonsterEnum.ZombieHypertensionGrandpa: {"weight": 30, "count": 8},
    MonsterEnum.ZombieJocker: {"weight": 30, "count": 4},
    MonsterEnum.ZombieJockerKing: {"weight": 30, "count": 2},
    MonsterEnum.ZombieOtakuBlack: {"weight": 30, "count": 6},
}

_MonsterPoolLv6 = {
    MonsterEnum.ZombieBig: {"weight": 30, "count": 6},
    MonsterEnum.ZombieGoldenChick: {"weight": 30, "count": 4},
    MonsterEnum.ZombieFlameVenom: {"weight": 30, "count": 5},
    MonsterEnum.ZombieBigDog: {"weight": 30, "count": 6},
    MonsterEnum.ZombieBlackVenom: {"weight": 30, "count": 3},
}

_MonsterPoolLv7 = {
    MonsterEnum.ZombieGiant: {"weight": 30, "count": 3},
    MonsterEnum.ZombieSarcoma: {"weight": 30, "count": 3},
    MonsterEnum.ZombieBigGiant: {"weight": 30, "count": 2},
    MonsterEnum.ZombieGiantKing: {"weight": 30, "count": 2},
    MonsterEnum.ZombieGiantSarcoma: {"weight": 30, "count": 2},
    MonsterEnum.ZombieFlyingLava: {"weight": 30, "count": 1}
}

_MonsterPoolLv8 = {
    MonsterEnum.ZombieFlyingLava: {"weight": 30, "count": 1}
}

_RebelPool = {
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 2},
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 3},
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 1},
    MonsterEnum.RebelSoilder: {"weight": 10, "count": 2},
}

Config = {
    'identifier': 'scuke_city_new:city_new_b_c',
    'structure_name_base': 'scuke_city_new:city_new',
    'is_feature_rule': True,
    'center': (176, 0, 192),
    'size': (360, 111, 388),
    'posMarkers': [
        {'pos': (10, 4, 21), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (12, 4, 84), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (9, 4, 129), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (12, 4, 191), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (27, 4, 21), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (27, 4, 24), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (24, 4, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (18, 4, 95), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (22, 4, 160), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (31, 4, 280), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (17, 4, 291), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (17, 4, 367), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (20, 4, 369), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (33, 4, 51), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (40, 4, 84), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (41, 4, 92), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (43, 4, 99), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (38, 4, 161), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (39, 4, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (44, 4, 164), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (47, 4, 170), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (40, 4, 176), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (39, 4, 255), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (43, 4, 257), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (38, 4, 301), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (46, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (55, 4, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (55, 24, 47), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (56, 30, 45), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (63, 30, 45), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (57, 4, 130), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (54, 4, 280), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (62, 4, 283), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (53, 4, 308), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (52, 4, 328), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (57, 4, 346), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (62, 4, 364), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (67, 4, 47), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (78, 18, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (77, 18, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (79, 4, 75), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (66, 11, 242), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (95, 4, 50), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (86, 4, 76), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (87, 4, 71), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (87, 4, 95), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (88, 4, 82), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (94, 4, 95), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (87, 19, 100), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (90, 31, 100), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (93, 38, 102), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (91, 4, 159), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (85, 25, 162), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (86, 19, 160), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (89, 5, 170), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (90, 31, 162), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (94, 4, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (90, 4, 191), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (86, 4, 196), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (93, 4, 195), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (84, 6, 211), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (87, 3, 235), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (88, 3, 239), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (89, 3, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (93, 3, 240), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (94, 4, 266), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (90, 4, 284), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (80, 4, 348), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (100, 4, 95), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (100, 4, 109), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (107, 25, 100), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (111, 4, 125), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (108, 4, 130), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (109, 4, 132), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (110, 4, 128), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (100, 38, 162), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (105, 4, 160), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (105, 19, 161), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (101, 4, 191), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (96, 4, 192), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (101, 3, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (106, 3, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (107, 4, 285), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (107, 4, 335), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (106, 4, 336), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (122, 4, 46), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (124, 19, 45), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (126, 4, 42), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (113, 38, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (113, 19, 163), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (116, 25, 162), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (120, 6, 261), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (114, 13, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (126, 8, 335), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (126, 18, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (115, 23, 340), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (124, 4, 372), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        
        {'pos': (139, 4, 8), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (131, 19, 43), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (139, 4, 45), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (139, 31, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (137, 4, 77), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (135, 4, 89), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (136, 4, 84), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (140, 4, 90), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (142, 4, 83), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (136, 4, 99), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (135, 4, 161), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (137, 4, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (135, 4, 194), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (135, 4, 224), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (135, 4, 232), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (140, 4, 228), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (137, 4, 252), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (135, 4, 299), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (141, 4, 303), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (130, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (136, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (136, 4, 307), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (129, 18, 331), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (136, 4, 365), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (137, 4, 367), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (143, 4, 372), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (146, 25, 40), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (158, 13, 102), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (158, 18, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (159, 28, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (151, 4, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (151, 23, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (152, 13, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (154, 13, 335), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (164, 4, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 43, 103), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (162, 13, 106), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (165, 23, 105), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 33, 106), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 38, 106), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv8},
        {'pos': (171, 38, 104), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (161, 18, 121), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 18, 125), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 28, 124), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 43, 117), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (174, 23, 115), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (163, 18, 130), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (164, 13, 129), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (164, 33, 132), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (166, 43, 138), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (171, 28, 136), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (160, 4, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (163, 38, 183), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (163, 43, 187), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (170, 33, 183), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (171, 38, 183), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (160, 21, 196), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (165, 8, 196), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (169, 8, 192), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 43, 192), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (160, 13, 215), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (160, 28, 215), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (163, 33, 210), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 28, 216), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 38, 214), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 4, 229), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (163, 23, 250), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (166, 13, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (173, 23, 255), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (161, 16, 259), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (165, 18, 270), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (164, 13, 277), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (167, 23, 276), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (172, 23, 279), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (172, 4, 328), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (171, 4, 347), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (179, 19, 43), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (191, 4, 42), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (185, 4, 55), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (187, 25, 52), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (181, 4, 89), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (186, 4, 112), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (188, 4, 112), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (179, 4, 152), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (182, 4, 154), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (182, 4, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (184, 4, 149), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (185, 4, 171), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (188, 4, 167), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (183, 4, 203), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (186, 4, 234), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (187, 4, 237), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (187, 4, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (186, 4, 283), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (181, 23, 340), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (196, 4, 8), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (198, 4, 5), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 4, 17), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (200, 4, 42), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 38, 47), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (206, 25, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (197, 31, 60), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (201, 28, 108), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (204, 23, 104), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (205, 8, 109), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 4, 117), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (206, 33, 121), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (198, 18, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (201, 23, 136), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 8, 136), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 33, 136), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 38, 136), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (203, 4, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 28, 185), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (204, 4, 186), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (204, 18, 182), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (204, 23, 185), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (205, 43, 180), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (198, 43, 207), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (203, 13, 207), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (199, 38, 214), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (200, 23, 215), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (203, 8, 210), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 13, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (201, 18, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (206, 23, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (204, 23, 280), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (193, 13, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (197, 13, 341), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (205, 4, 336), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 4, 370), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (208, 4, 23), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (208, 19, 46), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (209, 4, 75), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (212, 4, 78), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (213, 4, 74), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (211, 4, 81), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (211, 38, 103), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (208, 43, 131), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (212, 38, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (212, 38, 184), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (212, 28, 203), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (209, 4, 230), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (208, 8, 246), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (209, 13, 255), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (212, 23, 252), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (217, 8, 275), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (214, 18, 332), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (215, 23, 331), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (222, 4, 374), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (233, 4, 38), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (228, 4, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (233, 4, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (235, 4, 137), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (235, 4, 138), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (232, 4, 145), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (231, 4, 179), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (235, 4, 202), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (233, 4, 232), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (230, 4, 250), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (236, 4, 245), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (238, 4, 301), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (236, 4, 306), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (237, 4, 350), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (236, 4, 373), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (254, 43, 51), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (252, 4, 75), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (254, 4, 127), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (249, 12, 154), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (251, 28, 156), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (252, 20, 158), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (252, 36, 158), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (253, 12, 154), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (249, 36, 160), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (251, 4, 171), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (250, 20, 187), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (251, 28, 190), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (254, 28, 184), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (244, 4, 305), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (248, 4, 310), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (249, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (249, 4, 371), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv8},
        {'pos': (252, 4, 376), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (256, 4, 16), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (258, 18, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (259, 13, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (257, 18, 57), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (259, 33, 57), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (260, 18, 57), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (269, 38, 56), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (266, 4, 98), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (266, 4, 113), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (261, 4, 158), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (261, 28, 190), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (262, 12, 185), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (260, 28, 228), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (262, 36, 231), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (264, 12, 231), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (264, 36, 234), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (264, 60, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (270, 20, 229), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (270, 60, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (271, 44, 231), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (256, 4, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (259, 28, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (267, 4, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (260, 52, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (268, 44, 267), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (270, 20, 267), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (270, 36, 268), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (270, 44, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (265, 12, 272), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (270, 4, 278), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (262, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (257, 13, 335), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (261, 13, 337), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (270, 8, 337), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (272, 33, 50), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (284, 43, 56), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (287, 28, 55), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (276, 12, 146), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (284, 4, 191), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (274, 20, 229), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (274, 20, 233), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (278, 28, 235), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (282, 52, 246), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (285, 12, 249), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (274, 4, 270), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (280, 60, 267), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (274, 28, 280), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (278, 18, 332), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (279, 23, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (280, 18, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (285, 10, 376), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (291, 18, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (288, 38, 48), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (289, 28, 59), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (299, 4, 77), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (291, 4, 126), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (298, 4, 130), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (291, 36, 153), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (295, 20, 158), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (298, 28, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (293, 20, 163), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (293, 28, 164), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (298, 12, 161), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (301, 28, 171), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (294, 36, 183), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (295, 12, 185), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (295, 36, 181), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (296, 12, 191), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (300, 4, 193), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (290, 12, 225), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (294, 12, 256), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (309, 4, 33), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (313, 4, 77), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (318, 4, 77), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (314, 4, 80), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (316, 4, 88), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (317, 4, 80), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (310, 5, 195), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (312, 5, 202), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (315, 5, 195), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (316, 4, 207), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (316, 5, 199), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (313, 4, 214), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (311, 4, 314), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (316, 4, 318), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (310, 4, 320), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (311, 4, 321), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (311, 4, 350), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (335, 4, 71), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (333, 4, 91), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (333, 4, 125), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (333, 4, 274), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (333, 4, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (337, 4, 69), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (337, 4, 93), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (339, 4, 105), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (344, 4, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (346, 4, 284), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (336, 4, 291), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
    ]
}
