# -*- coding: utf-8 -*-
from ScukeSurviveScript.modCommon.defines.monsterEnum import MonsterEnum

_MonsterPoolLv1 = {
    MonsterEnum.ZombieNormal: {"weight": 30, "count": 4},
    MonsterEnum.ZombieGangs: {"weight": 30, "count": 4},
    MonsterEnum.ZombieChick: {"weight": 30, "count": 4},
}

_MonsterPoolLv2 = {
    MonsterEnum.ZombieCaptain: {"weight": 30, "count": 3},
    MonsterEnum.ZombieDog: {"weight": 30, "count": 6},
    MonsterEnum.ZombieExplosive: {"weight": 30, "count": 4},
}

_MonsterPoolLv3 = {
    MonsterEnum.ZombieGuard: {"weight": 30, "count": 3},
    MonsterEnum.ZombieFat: {"weight": 30, "count": 4},
    MonsterEnum.ZombieGrandpa: {"weight": 30, "count": 5},
    MonsterEnum.ZombieSuperTNT: {"weight": 30, "count": 2},
}

_MonsterPoolLv4 = {
    MonsterEnum.ZombieOtaku: {"weight": 30, "count": 5},
    MonsterEnum.ZombieGangsCaptain: {"weight": 30, "count": 6},
    MonsterEnum.ZombieVenom: {"weight": 30, "count": 5},
    MonsterEnum.ZombieSpicyChick: {"weight": 30, "count": 7},
    MonsterEnum.ZombieTonsKing: {"weight": 30, "count": 4},
}

_MonsterPoolLv5 = {
    MonsterEnum.ZombieSpecialGuard: {"weight": 30, "count": 5},
    MonsterEnum.ZombieHypertensionGrandpa: {"weight": 30, "count": 8},
    MonsterEnum.ZombieJocker: {"weight": 30, "count": 4},
    MonsterEnum.ZombieJockerKing: {"weight": 30, "count": 2},
    MonsterEnum.ZombieOtakuBlack: {"weight": 30, "count": 6},
}

_MonsterPoolLv6 = {
    MonsterEnum.ZombieBig: {"weight": 30, "count": 6},
    MonsterEnum.ZombieGoldenChick: {"weight": 30, "count": 4},
    MonsterEnum.ZombieFlameVenom: {"weight": 30, "count": 5},
    MonsterEnum.ZombieBigDog: {"weight": 30, "count": 6},
    MonsterEnum.ZombieBlackVenom: {"weight": 30, "count": 3},
}

_MonsterPoolLv7 = {
    MonsterEnum.ZombieGiant: {"weight": 30, "count": 3},
    MonsterEnum.ZombieSarcoma: {"weight": 30, "count": 3},
    MonsterEnum.ZombieBigGiant: {"weight": 30, "count": 2},
    MonsterEnum.ZombieGiantKing: {"weight": 30, "count": 2},
    MonsterEnum.ZombieGiantSarcoma: {"weight": 30, "count": 2},
}

_MonsterPoolLv8 = {
    MonsterEnum.ZombieFlyingLava: {"weight": 30, "count": 1}
}

_RebelPool = {
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 2},
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 3},
    MonsterEnum.RebelSoilder: {"weight": 30, "count": 1},
    MonsterEnum.RebelSoilder: {"weight": 10, "count": 2},
}

Config = {
    'identifier': 'scuke_city_broken:city_broken_b_c',
    'structure_name_base': 'scuke_city_broken:city_broken',
    'is_feature_rule': True,
    'center': (176, 0, 192),
    'size': (359, 95, 395),
    'posMarkers': [
        {'pos': (12, 4, 68), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (11, 4, 198), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (10, 4, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (26, 4, 16), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (31, 4, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (26, 4, 137), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (16, 4, 264), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (30, 4, 332), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (42, 4, 98), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (44, 4, 155), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (45, 4, 159), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (44, 4, 163), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (45, 4, 173), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (45, 4, 214), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (37, 4, 234), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (44, 5, 261), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (42, 4, 286), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (34, 4, 293), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (51, 4, 14), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (51, 5, 19), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (55, 4, 57), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (63, 18, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (61, 4, 215), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (59, 4, 304), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (57, 4, 348), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (57, 4, 377), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (72, 24, 50), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (68, 4, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (69, 4, 195), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (64, 3, 241), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (69, 4, 271), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (72, 4, 265), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (79, 4, 303), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (79, 4, 306), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (75, 3, 324), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (89, 4, 43), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (91, 19, 101), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (95, 25, 101), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (86, 4, 132), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (93, 4, 148), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (89, 25, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (88, 4, 202), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (88, 3, 238), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (85, 3, 241), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (86, 4, 271), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (90, 4, 312), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (92, 4, 308), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (94, 4, 312), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (93, 4, 358), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (98, 4, 55), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (98, 4, 109), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (97, 31, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (102, 31, 162), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (106, 4, 163), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (107, 25, 163), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (107, 4, 197), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (110, 4, 198), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (101, 3, 241), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (97, 4, 281), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (106, 4, 274), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (126, 19, 48), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (126, 25, 50), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (123, 4, 81), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (118, 4, 133), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (114, 19, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (116, 4, 217), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (120, 3, 326), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},
        {'pos': (123, 18, 346), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _RebelPool},

        {'pos': (130, 31, 47), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (139, 40, 51), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (134, 4, 85), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (139, 4, 97), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (133, 4, 127), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (142, 4, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (134, 4, 198), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (141, 4, 215), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (132, 4, 226), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (136, 4, 224), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (130, 4, 254), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (141, 4, 251), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (136, 4, 303), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (128, 8, 337), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (157, 23, 106), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (153, 28, 182), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (154, 28, 192), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (156, 44, 211), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (153, 4, 229), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (159, 18, 272), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (154, 4, 305), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (146, 24, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (145, 3, 378), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (163, 4, 47), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 4, 82), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (168, 44, 106), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (168, 44, 121), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (160, 38, 188), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 23, 188), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (162, 18, 203), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 23, 227), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (162, 23, 225), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (164, 18, 254), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (161, 6, 262), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv8},
        {'pos': (164, 13, 274), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (166, 8, 285), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (170, 4, 303), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (169, 4, 306), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (169, 4, 333), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (169, 4, 356), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (179, 19, 48), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (181, 5, 51), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (182, 4, 111), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (179, 4, 143), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (186, 4, 153), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (186, 4, 178), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (186, 4, 210), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (186, 4, 242), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (182, 4, 284), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (179, 4, 305), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (190, 13, 352), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 5, 56), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (204, 25, 48), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (206, 19, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (199, 44, 107), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (201, 18, 98), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (194, 23, 131), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (195, 4, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (203, 44, 187), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (197, 16, 198), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (200, 33, 212), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (202, 33, 221), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (192, 3, 245), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (207, 24, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (201, 8, 280), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (213, 4, 20), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (210, 38, 105), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (211, 38, 108), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (212, 23, 132), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (211, 39, 148), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (210, 13, 190), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (210, 14, 199), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (211, 18, 244), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (208, 18, 285), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (210, 24, 334), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (212, 18, 336), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (213, 13, 341), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (232, 4, 45), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (231, 4, 62), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (229, 4, 84), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (230, 4, 89), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (230, 4, 114), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (234, 4, 123), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (235, 4, 158), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (232, 4, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (234, 4, 170), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (229, 4, 176), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (233, 4, 223), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (230, 4, 230), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (231, 4, 247), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (226, 4, 267), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (234, 4, 259), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (232, 4, 281), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (237, 4, 307), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (235, 4, 376), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (254, 18, 46), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (248, 39, 60), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (248, 4, 80), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (254, 4, 82), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (252, 4, 129), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (249, 4, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (249, 28, 157), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (252, 12, 159), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (251, 37, 175), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (253, 20, 164), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (251, 20, 187), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (251, 28, 185), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (252, 4, 184), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (252, 20, 187), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (253, 12, 179), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (255, 44, 275), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (247, 4, 306), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (251, 4, 307), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (252, 13, 346), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (247, 4, 360), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (260, 23, 59), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (261, 4, 77), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (259, 4, 116), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (266, 4, 116), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (259, 20, 153), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (260, 12, 169), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (267, 36, 221), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv7},
        {'pos': (262, 28, 226), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (263, 60, 239), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (264, 20, 236), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (267, 44, 231), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (267, 52, 236), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (258, 4, 251), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (263, 28, 250), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (263, 36, 251), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (260, 60, 256), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (265, 52, 261), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (267, 12, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (271, 12, 260), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (268, 28, 276), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (269, 20, 274), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (257, 13, 339), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (280, 23, 44), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (274, 44, 57), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (279, 33, 61), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (281, 38, 49), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (276, 4, 78), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (287, 4, 81), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (275, 4, 108), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (276, 4, 105), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv5},
        {'pos': (286, 4, 103), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (276, 4, 135), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (285, 28, 183), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (275, 4, 207), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (275, 4, 223), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (274, 44, 238), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (278, 20, 238), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (278, 28, 237), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (276, 60, 242), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (282, 4, 244), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (272, 4, 269), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (274, 60, 270), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (277, 36, 270), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (272, 36, 277), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (277, 44, 285), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (278, 20, 278), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (285, 4, 272), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (275, 24, 344), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (275, 24, 345), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (279, 13, 340), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (285, 18, 347), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (279, 4, 381), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (291, 4, 11), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (289, 23, 60), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (290, 33, 60), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (293, 8, 61), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (292, 4, 84), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (293, 4, 116), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (288, 16, 130), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (289, 28, 154), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (292, 12, 156), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (294, 28, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (294, 36, 173), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (293, 12, 184), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv3},
        {'pos': (296, 4, 190), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (291, 12, 192), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (288, 44, 223), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (313, 4, 131), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (318, 4, 133), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (309, 5, 166), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (312, 5, 170), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (316, 5, 165), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (315, 4, 222), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv8},
        {'pos': (308, 4, 236), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (312, 4, 224), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (309, 4, 273), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (317, 4, 273), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv4},
        {'pos': (309, 4, 358), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (310, 4, 355), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (334, 4, 275), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (320, 4, 317), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (338, 4, 35), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (347, 4, 36), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (340, 4, 147), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
        {'pos': (341, 4, 219), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv2},
        {'pos': (336, 4, 247), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv6},
        {'pos': (342, 4, 358), 'id': 'scuke_survive:monster_pool', 'face': 0, 'entity_pool': _MonsterPoolLv1},
    ]
}
